
import { Suggestion } from './types';

// $0 represents where the cursor will be placed after insertion

export const HTML_ATTRIBUTES: Suggestion[] = [
    { label: 'accept', value: 'accept="image/*"', type: 'property', detail: 'Form Accept' },
    { label: 'accept-charset', value: 'accept-charset="UTF-8"', type: 'property', detail: 'Form Charset' },
    { label: 'accesskey', value: 'accesskey="$0"', type: 'property', detail: 'Shortcut Key' },
    { label: 'action', value: 'action="$0"', type: 'property', detail: 'Form Action' },
    { label: 'align', value: 'align="center"', type: 'property', detail: 'Align (Deprecated)' },
    { label: 'allow', value: 'allow="camera; microphone"', type: 'property', detail: 'Iframe Policy' },
    { label: 'alt', value: 'alt="$0"', type: 'property', detail: 'Alt Text' },
    { label: 'aria-atomic', value: 'aria-atomic="true"', type: 'property', detail: 'ARIA Atomic' },
    { label: 'aria-autocomplete', value: 'aria-autocomplete="both"', type: 'property', detail: 'ARIA Autocomplete' },
    { label: 'aria-busy', value: 'aria-busy="true"', type: 'property', detail: 'ARIA Busy' },
    { label: 'aria-checked', value: 'aria-checked="true"', type: 'property', detail: 'ARIA Checked' },
    { label: 'aria-colcount', value: 'aria-colcount="10"', type: 'property', detail: 'ARIA Col Count' },
    { label: 'aria-colindex', value: 'aria-colindex="1"', type: 'property', detail: 'ARIA Col Index' },
    { label: 'aria-controls', value: 'aria-controls="$0"', type: 'property', detail: 'ARIA Controls' },
    { label: 'aria-current', value: 'aria-current="page"', type: 'property', detail: 'ARIA Current' },
    { label: 'aria-describedby', value: 'aria-describedby="$0"', type: 'property', detail: 'ARIA Described By' },
    { label: 'aria-details', value: 'aria-details="$0"', type: 'property', detail: 'ARIA Details' },
    { label: 'aria-disabled', value: 'aria-disabled="true"', type: 'property', detail: 'ARIA Disabled' },
    { label: 'aria-expanded', value: 'aria-expanded="false"', type: 'property', detail: 'ARIA Expanded' },
    { label: 'aria-haspopup', value: 'aria-haspopup="true"', type: 'property', detail: 'ARIA Has Popup' },
    { label: 'aria-hidden', value: 'aria-hidden="true"', type: 'property', detail: 'ARIA Hidden' },
    { label: 'aria-invalid', value: 'aria-invalid="true"', type: 'property', detail: 'ARIA Invalid' },
    { label: 'aria-keyshortcuts', value: 'aria-keyshortcuts="$0"', type: 'property', detail: 'ARIA Shortcuts' },
    { label: 'aria-label', value: 'aria-label="$0"', type: 'property', detail: 'ARIA Label' },
    { label: 'aria-labelledby', value: 'aria-labelledby="$0"', type: 'property', detail: 'ARIA Labelled By' },
    { label: 'aria-level', value: 'aria-level="1"', type: 'property', detail: 'ARIA Level' },
    { label: 'aria-live', value: 'aria-live="polite"', type: 'property', detail: 'ARIA Live' },
    { label: 'aria-modal', value: 'aria-modal="true"', type: 'property', detail: 'ARIA Modal' },
    { label: 'aria-multiline', value: 'aria-multiline="true"', type: 'property', detail: 'ARIA Multiline' },
    { label: 'aria-multiselectable', value: 'aria-multiselectable="true"', type: 'property', detail: 'ARIA Multiselectable' },
    { label: 'aria-orientation', value: 'aria-orientation="horizontal"', type: 'property', detail: 'ARIA Orientation' },
    { label: 'aria-owns', value: 'aria-owns="$0"', type: 'property', detail: 'ARIA Owns' },
    { label: 'aria-placeholder', value: 'aria-placeholder="$0"', type: 'property', detail: 'ARIA Placeholder' },
    { label: 'aria-posinset', value: 'aria-posinset="1"', type: 'property', detail: 'ARIA Pos In Set' },
    { label: 'aria-pressed', value: 'aria-pressed="false"', type: 'property', detail: 'ARIA Pressed' },
    { label: 'aria-readonly', value: 'aria-readonly="true"', type: 'property', detail: 'ARIA Readonly' },
    { label: 'aria-required', value: 'aria-required="true"', type: 'property', detail: 'ARIA Required' },
    { label: 'aria-roledescription', value: 'aria-roledescription="$0"', type: 'property', detail: 'ARIA Role Desc' },
    { label: 'aria-rowcount', value: 'aria-rowcount="10"', type: 'property', detail: 'ARIA Row Count' },
    { label: 'aria-rowindex', value: 'aria-rowindex="1"', type: 'property', detail: 'ARIA Row Index' },
    { label: 'aria-selected', value: 'aria-selected="true"', type: 'property', detail: 'ARIA Selected' },
    { label: 'aria-setsize', value: 'aria-setsize="10"', type: 'property', detail: 'ARIA Set Size' },
    { label: 'aria-sort', value: 'aria-sort="ascending"', type: 'property', detail: 'ARIA Sort' },
    { label: 'aria-valuemax', value: 'aria-valuemax="100"', type: 'property', detail: 'ARIA Value Max' },
    { label: 'aria-valuemin', value: 'aria-valuemin="0"', type: 'property', detail: 'ARIA Value Min' },
    { label: 'aria-valuenow', value: 'aria-valuenow="50"', type: 'property', detail: 'ARIA Value Now' },
    { label: 'aria-valuetext', value: 'aria-valuetext="$0"', type: 'property', detail: 'ARIA Value Text' },
    { label: 'async', value: 'async', type: 'property', detail: 'Async Script' },
    { label: 'autocapitalize', value: 'autocapitalize="off"', type: 'property', detail: 'Auto Capitalize' },
    { label: 'autocomplete', value: 'autocomplete="off"', type: 'property', detail: 'Auto Complete' },
    { label: 'autofocus', value: 'autofocus', type: 'property', detail: 'Auto Focus' },
    { label: 'autoplay', value: 'autoplay', type: 'property', detail: 'Auto Play' },
    { label: 'bgcolor', value: 'bgcolor="#ffffff"', type: 'property', detail: 'BG Color (Dep)' },
    { label: 'border', value: 'border="0"', type: 'property', detail: 'Border Width' },
    { label: 'capture', value: 'capture="environment"', type: 'property', detail: 'Media Capture' },
    { label: 'cellpadding', value: 'cellpadding="0"', type: 'property', detail: 'Cell Padding' },
    { label: 'cellspacing', value: 'cellspacing="0"', type: 'property', detail: 'Cell Spacing' },
    { label: 'charset', value: 'charset="UTF-8"', type: 'property', detail: 'Charset' },
    { label: 'checked', value: 'checked', type: 'property', detail: 'Checked State' },
    { label: 'cite', value: 'cite="$0"', type: 'property', detail: 'Citation URL' },
    { label: 'class', value: 'class="$0"', type: 'property', detail: 'CSS Class' },
    { label: 'clip-path', value: 'clip-path="url(#$0)"', type: 'property', detail: 'SVG Clip Path' },
    { label: 'cols', value: 'cols="30"', type: 'property', detail: 'Columns' },
    { label: 'colspan', value: 'colspan="1"', type: 'property', detail: 'Column Span' },
    { label: 'content', value: 'content="$0"', type: 'property', detail: 'Meta Content' },
    { label: 'contenteditable', value: 'contenteditable="true"', type: 'property', detail: 'Editable' },
    { label: 'controls', value: 'controls', type: 'property', detail: 'Media Controls' },
    { label: 'coords', value: 'coords="$0"', type: 'property', detail: 'Area Coords' },
    { label: 'crossorigin', value: 'crossorigin="anonymous"', type: 'property', detail: 'CORS Settings' },
    { label: 'cx', value: 'cx="50"', type: 'property', detail: 'SVG Center X' },
    { label: 'cy', value: 'cy="50"', type: 'property', detail: 'SVG Center Y' },
    { label: 'd', value: 'd="$0"', type: 'property', detail: 'SVG Path Data' },
    { label: 'data', value: 'data="$0"', type: 'property', detail: 'Object Data' },
    { label: 'datetime', value: 'datetime="$0"', type: 'property', detail: 'Datetime' },
    { label: 'decoding', value: 'decoding="async"', type: 'property', detail: 'Image Decoding' },
    { label: 'default', value: 'default', type: 'property', detail: 'Default Track' },
    { label: 'defer', value: 'defer', type: 'property', detail: 'Defer Script' },
    { label: 'dir', value: 'dir="ltr"', type: 'property', detail: 'Text Direction' },
    { label: 'dirname', value: 'dirname="$0"', type: 'property', detail: 'Dir Name' },
    { label: 'disabled', value: 'disabled', type: 'property', detail: 'Disabled State' },
    { label: 'download', value: 'download="$0"', type: 'property', detail: 'Download Link' },
    { label: 'draggable', value: 'draggable="true"', type: 'property', detail: 'Draggable' },
    { label: 'enctype', value: 'enctype="multipart/form-data"', type: 'property', detail: 'Form Encoding' },
    { label: 'enterkeyhint', value: 'enterkeyhint="go"', type: 'property', detail: 'Enter Key Hint' },
    { label: 'fill', value: 'fill="currentColor"', type: 'property', detail: 'SVG Fill' },
    { label: 'fill-opacity', value: 'fill-opacity="1"', type: 'property', detail: 'SVG Fill Opacity' },
    { label: 'fill-rule', value: 'fill-rule="evenodd"', type: 'property', detail: 'SVG Fill Rule' },
    { label: 'for', value: 'for="$0"', type: 'property', detail: 'Label For' },
    { label: 'form', value: 'form="$0"', type: 'property', detail: 'Form Owner' },
    { label: 'formaction', value: 'formaction="$0"', type: 'property', detail: 'Form Action' },
    { label: 'formenctype', value: 'formenctype="multipart/form-data"', type: 'property', detail: 'Form Enctype' },
    { label: 'formmethod', value: 'formmethod="post"', type: 'property', detail: 'Form Method' },
    { label: 'formnovalidate', value: 'formnovalidate', type: 'property', detail: 'Form No Validate' },
    { label: 'formtarget', value: 'formtarget="_blank"', type: 'property', detail: 'Form Target' },
    { label: 'fx', value: 'fx="0"', type: 'property', detail: 'SVG Focal X' },
    { label: 'fy', value: 'fy="0"', type: 'property', detail: 'SVG Focal Y' },
    { label: 'gradientTransform', value: 'gradientTransform="rotate(45)"', type: 'property', detail: 'SVG Grad Trans' },
    { label: 'gradientUnits', value: 'gradientUnits="userSpaceOnUse"', type: 'property', detail: 'SVG Grad Units' },
    { label: 'headers', value: 'headers="$0"', type: 'property', detail: 'Table Headers' },
    { label: 'height', value: 'height="$0"', type: 'property', detail: 'Height' },
    { label: 'hidden', value: 'hidden', type: 'property', detail: 'Hidden' },
    { label: 'high', value: 'high="0"', type: 'property', detail: 'Meter High' },
    { label: 'href', value: 'href="$0"', type: 'property', detail: 'Hyperlink Ref' },
    { label: 'hreflang', value: 'hreflang="en"', type: 'property', detail: 'Link Lang' },
    { label: 'http-equiv', value: 'http-equiv="$0"', type: 'property', detail: 'Meta HTTP' },
    { label: 'id', value: 'id="$0"', type: 'property', detail: 'Unique ID' },
    { label: 'inputmode', value: 'inputmode="text"', type: 'property', detail: 'Input Mode' },
    { label: 'integrity', value: 'integrity="$0"', type: 'property', detail: 'Subresource Integrity' },
    { label: 'is', value: 'is="$0"', type: 'property', detail: 'Custom Element IS' },
    { label: 'itemid', value: 'itemid="$0"', type: 'property', detail: 'Microdata ID' },
    { label: 'itemprop', value: 'itemprop="$0"', type: 'property', detail: 'Microdata Prop' },
    { label: 'itemref', value: 'itemref="$0"', type: 'property', detail: 'Microdata Ref' },
    { label: 'itemscope', value: 'itemscope', type: 'property', detail: 'Microdata Scope' },
    { label: 'itemtype', value: 'itemtype="https://schema.org/$0"', type: 'property', detail: 'Microdata Type' },
    { label: 'kind', value: 'kind="subtitles"', type: 'property', detail: 'Track Kind' },
    { label: 'label', value: 'label="$0"', type: 'property', detail: 'Track Label' },
    { label: 'lang', value: 'lang="en"', type: 'property', detail: 'Language' },
    { label: 'list', value: 'list="$0"', type: 'property', detail: 'Datalist ID' },
    { label: 'loading', value: 'loading="lazy"', type: 'property', detail: 'Lazy Loading' },
    { label: 'loop', value: 'loop', type: 'property', detail: 'Media Loop' },
    { label: 'low', value: 'low="0"', type: 'property', detail: 'Meter Low' },
    { label: 'marker-end', value: 'marker-end="url(#$0)"', type: 'property', detail: 'SVG Marker End' },
    { label: 'marker-mid', value: 'marker-mid="url(#$0)"', type: 'property', detail: 'SVG Marker Mid' },
    { label: 'marker-start', value: 'marker-start="url(#$0)"', type: 'property', detail: 'SVG Marker Start' },
    { label: 'mask', value: 'mask="url(#$0)"', type: 'property', detail: 'SVG Mask' },
    { label: 'max', value: 'max="100"', type: 'property', detail: 'Max Value' },
    { label: 'maxlength', value: 'maxlength="255"', type: 'property', detail: 'Max Length' },
    { label: 'media', value: 'media="(min-width: 600px)"', type: 'property', detail: 'Media Query' },
    { label: 'method', value: 'method="POST"', type: 'property', detail: 'Form Method' },
    { label: 'min', value: 'min="0"', type: 'property', detail: 'Min Value' },
    { label: 'minlength', value: 'minlength="0"', type: 'property', detail: 'Min Length' },
    { label: 'multiple', value: 'multiple', type: 'property', detail: 'Multiple' },
    { label: 'muted', value: 'muted', type: 'property', detail: 'Media Muted' },
    { label: 'name', value: 'name="$0"', type: 'property', detail: 'Name' },
    { label: 'nonce', value: 'nonce="$0"', type: 'property', detail: 'Nonce' },
    { label: 'novalidate', value: 'novalidate', type: 'property', detail: 'No Validation' },
    { label: 'offset', value: 'offset="0%"', type: 'property', detail: 'SVG Offset' },
    { label: 'onabort', value: 'onabort="$0"', type: 'property', detail: 'Event: Abort' },
    { label: 'onblur', value: 'onblur="$0"', type: 'property', detail: 'Event: Blur' },
    { label: 'oncancel', value: 'oncancel="$0"', type: 'property', detail: 'Event: Cancel' },
    { label: 'oncanplay', value: 'oncanplay="$0"', type: 'property', detail: 'Event: Can Play' },
    { label: 'oncanplaythrough', value: 'oncanplaythrough="$0"', type: 'property', detail: 'Event: Can Play Through' },
    { label: 'onchange', value: 'onchange="$0"', type: 'property', detail: 'Event: Change' },
    { label: 'onclick', value: 'onclick="$0"', type: 'property', detail: 'Event: Click' },
    { label: 'oncontextmenu', value: 'oncontextmenu="$0"', type: 'property', detail: 'Event: Context Menu' },
    { label: 'oncopy', value: 'oncopy="$0"', type: 'property', detail: 'Event: Copy' },
    { label: 'oncut', value: 'oncut="$0"', type: 'property', detail: 'Event: Cut' },
    { label: 'ondblclick', value: 'ondblclick="$0"', type: 'property', detail: 'Event: Double Click' },
    { label: 'ondrag', value: 'ondrag="$0"', type: 'property', detail: 'Event: Drag' },
    { label: 'ondragend', value: 'ondragend="$0"', type: 'property', detail: 'Event: Drag End' },
    { label: 'ondragenter', value: 'ondragenter="$0"', type: 'property', detail: 'Event: Drag Enter' },
    { label: 'ondragleave', value: 'ondragleave="$0"', type: 'property', detail: 'Event: Drag Leave' },
    { label: 'ondragover', value: 'ondragover="$0"', type: 'property', detail: 'Event: Drag Over' },
    { label: 'ondragstart', value: 'ondragstart="$0"', type: 'property', detail: 'Event: Drag Start' },
    { label: 'ondrop', value: 'ondrop="$0"', type: 'property', detail: 'Event: Drop' },
    { label: 'ondurationchange', value: 'ondurationchange="$0"', type: 'property', detail: 'Event: Duration Change' },
    { label: 'onended', value: 'onended="$0"', type: 'property', detail: 'Event: Ended' },
    { label: 'onerror', value: 'onerror="$0"', type: 'property', detail: 'Event: Error' },
    { label: 'onfocus', value: 'onfocus="$0"', type: 'property', detail: 'Event: Focus' },
    { label: 'oninput', value: 'oninput="$0"', type: 'property', detail: 'Event: Input' },
    { label: 'oninvalid', value: 'oninvalid="$0"', type: 'property', detail: 'Event: Invalid' },
    { label: 'onkeydown', value: 'onkeydown="$0"', type: 'property', detail: 'Event: Key Down' },
    { label: 'onkeypress', value: 'onkeypress="$0"', type: 'property', detail: 'Event: Key Press' },
    { label: 'onkeyup', value: 'onkeyup="$0"', type: 'property', detail: 'Event: Key Up' },
    { label: 'onload', value: 'onload="$0"', type: 'property', detail: 'Event: Load' },
    { label: 'onloadeddata', value: 'onloadeddata="$0"', type: 'property', detail: 'Event: Loaded Data' },
    { label: 'onloadedmetadata', value: 'onloadedmetadata="$0"', type: 'property', detail: 'Event: Loaded Meta' },
    { label: 'onloadstart', value: 'onloadstart="$0"', type: 'property', detail: 'Event: Load Start' },
    { label: 'onmousedown', value: 'onmousedown="$0"', type: 'property', detail: 'Event: Mouse Down' },
    { label: 'onmouseenter', value: 'onmouseenter="$0"', type: 'property', detail: 'Event: Mouse Enter' },
    { label: 'onmouseleave', value: 'onmouseleave="$0"', type: 'property', detail: 'Event: Mouse Leave' },
    { label: 'onmousemove', value: 'onmousemove="$0"', type: 'property', detail: 'Event: Mouse Move' },
    { label: 'onmouseout', value: 'onmouseout="$0"', type: 'property', detail: 'Event: Mouse Out' },
    { label: 'onmouseover', value: 'onmouseover="$0"', type: 'property', detail: 'Event: Mouse Over' },
    { label: 'onmouseup', value: 'onmouseup="$0"', type: 'property', detail: 'Event: Mouse Up' },
    { label: 'onpaste', value: 'onpaste="$0"', type: 'property', detail: 'Event: Paste' },
    { label: 'onpause', value: 'onpause="$0"', type: 'property', detail: 'Event: Pause' },
    { label: 'onplay', value: 'onplay="$0"', type: 'property', detail: 'Event: Play' },
    { label: 'onplaying', value: 'onplaying="$0"', type: 'property', detail: 'Event: Playing' },
    { label: 'onprogress', value: 'onprogress="$0"', type: 'property', detail: 'Event: Progress' },
    { label: 'onratechange', value: 'onratechange="$0"', type: 'property', detail: 'Event: Rate Change' },
    { label: 'onreset', value: 'onreset="$0"', type: 'property', detail: 'Event: Reset' },
    { label: 'onresize', value: 'onresize="$0"', type: 'property', detail: 'Event: Resize' },
    { label: 'onscroll', value: 'onscroll="$0"', type: 'property', detail: 'Event: Scroll' },
    { label: 'onsearch', value: 'onsearch="$0"', type: 'property', detail: 'Event: Search' },
    { label: 'onseeked', value: 'onseeked="$0"', type: 'property', detail: 'Event: Seeked' },
    { label: 'onseeking', value: 'onseeking="$0"', type: 'property', detail: 'Event: Seeking' },
    { label: 'onselect', value: 'onselect="$0"', type: 'property', detail: 'Event: Select' },
    { label: 'onsubmit', value: 'onsubmit="$0"', type: 'property', detail: 'Event: Submit' },
    { label: 'ontoggle', value: 'ontoggle="$0"', type: 'property', detail: 'Event: Toggle' },
    { label: 'ontouchcancel', value: 'ontouchcancel="$0"', type: 'property', detail: 'Event: Touch Cancel' },
    { label: 'ontouchend', value: 'ontouchend="$0"', type: 'property', detail: 'Event: Touch End' },
    { label: 'ontouchmove', value: 'ontouchmove="$0"', type: 'property', detail: 'Event: Touch Move' },
    { label: 'ontouchstart', value: 'ontouchstart="$0"', type: 'property', detail: 'Event: Touch Start' },
    { label: 'onvolumechange', value: 'onvolumechange="$0"', type: 'property', detail: 'Event: Volume Change' },
    { label: 'onwheel', value: 'onwheel="$0"', type: 'property', detail: 'Event: Wheel' },
    { label: 'opacity', value: 'opacity="1"', type: 'property', detail: 'SVG Opacity' },
    { label: 'open', value: 'open', type: 'property', detail: 'Details Open' },
    { label: 'optimum', value: 'optimum="0"', type: 'property', detail: 'Meter Optimum' },
    { label: 'part', value: 'part="$0"', type: 'property', detail: 'Shadow Part' },
    { label: 'pattern', value: 'pattern="$0"', type: 'property', detail: 'Regex Pattern' },
    { label: 'patternContentUnits', value: 'patternContentUnits="objectBoundingBox"', type: 'property', detail: 'SVG Pattern Content' },
    { label: 'patternUnits', value: 'patternUnits="objectBoundingBox"', type: 'property', detail: 'SVG Pattern Units' },
    { label: 'placeholder', value: 'placeholder="$0"', type: 'property', detail: 'Placeholder' },
    { label: 'playsinline', value: 'playsinline', type: 'property', detail: 'Inline Play' },
    { label: 'points', value: 'points="$0"', type: 'property', detail: 'SVG Points' },
    { label: 'poster', value: 'poster="$0"', type: 'property', detail: 'Video Poster' },
    { label: 'preload', value: 'preload="auto"', type: 'property', detail: 'Preload Media' },
    { label: 'preserveAspectRatio', value: 'preserveAspectRatio="xMidYMid meet"', type: 'property', detail: 'SVG Aspect Ratio' },
    { label: 'r', value: 'r="50"', type: 'property', detail: 'SVG Radius' },
    { label: 'readonly', value: 'readonly', type: 'property', detail: 'Readonly' },
    { label: 'referrerpolicy', value: 'referrerpolicy="no-referrer"', type: 'property', detail: 'Referrer Policy' },
    { label: 'rel', value: 'rel="noopener noreferrer"', type: 'property', detail: 'Link Rel' },
    { label: 'required', value: 'required', type: 'property', detail: 'Required' },
    { label: 'reversed', value: 'reversed', type: 'property', detail: 'Reversed List' },
    { label: 'role', value: 'role="$0"', type: 'property', detail: 'ARIA Role' },
    { label: 'rows', value: 'rows="10"', type: 'property', detail: 'Rows' },
    { label: 'rowspan', value: 'rowspan="1"', type: 'property', detail: 'Row Span' },
    { label: 'rx', value: 'rx="5"', type: 'property', detail: 'SVG Radius X' },
    { label: 'ry', value: 'ry="5"', type: 'property', detail: 'SVG Radius Y' },
    { label: 'sandbox', value: 'sandbox=""', type: 'property', detail: 'Iframe Sandbox' },
    { label: 'scope', value: 'scope="col"', type: 'property', detail: 'Header Scope' },
    { label: 'selected', value: 'selected', type: 'property', detail: 'Option Selected' },
    { label: 'shape', value: 'shape="rect"', type: 'property', detail: 'Area Shape' },
    { label: 'size', value: 'size="50"', type: 'property', detail: 'Input Size' },
    { label: 'sizes', value: 'sizes="(max-width: 600px) 100vw, 50vw"', type: 'property', detail: 'Image Sizes' },
    { label: 'slot', value: 'slot="$0"', type: 'property', detail: 'Slot Name' },
    { label: 'span', value: 'span="1"', type: 'property', detail: 'Col Span' },
    { label: 'spellcheck', value: 'spellcheck="false"', type: 'property', detail: 'Spellcheck' },
    { label: 'spreadMethod', value: 'spreadMethod="pad"', type: 'property', detail: 'SVG Spread' },
    { label: 'src', value: 'src="$0"', type: 'property', detail: 'Source URL' },
    { label: 'srcdoc', value: 'srcdoc="$0"', type: 'property', detail: 'Iframe Source' },
    { label: 'srclang', value: 'srclang="en"', type: 'property', detail: 'Track Lang' },
    { label: 'srcset', value: 'srcset="$0"', type: 'property', detail: 'Source Set' },
    { label: 'start', value: 'start="1"', type: 'property', detail: 'List Start' },
    { label: 'step', value: 'step="1"', type: 'property', detail: 'Input Step' },
    { label: 'stop-color', value: 'stop-color="currentColor"', type: 'property', detail: 'SVG Stop Color' },
    { label: 'stop-opacity', value: 'stop-opacity="1"', type: 'property', detail: 'SVG Stop Opacity' },
    { label: 'stroke', value: 'stroke="currentColor"', type: 'property', detail: 'SVG Stroke' },
    { label: 'stroke-dasharray', value: 'stroke-dasharray="4 2"', type: 'property', detail: 'SVG Dasharray' },
    { label: 'stroke-dashoffset', value: 'stroke-dashoffset="0"', type: 'property', detail: 'SVG Dashoffset' },
    { label: 'stroke-linecap', value: 'stroke-linecap="round"', type: 'property', detail: 'SVG Linecap' },
    { label: 'stroke-linejoin', value: 'stroke-linejoin="round"', type: 'property', detail: 'SVG Linejoin' },
    { label: 'stroke-miterlimit', value: 'stroke-miterlimit="4"', type: 'property', detail: 'SVG Miterlimit' },
    { label: 'stroke-opacity', value: 'stroke-opacity="1"', type: 'property', detail: 'SVG Stroke Opacity' },
    { label: 'stroke-width', value: 'stroke-width="2"', type: 'property', detail: 'SVG Stroke Width' },
    { label: 'style', value: 'style="$0"', type: 'property', detail: 'Inline Style' },
    { label: 'tabindex', value: 'tabindex="0"', type: 'property', detail: 'Tab Index' },
    { label: 'target', value: 'target="_blank"', type: 'property', detail: 'Link Target' },
    { label: 'text-anchor', value: 'text-anchor="middle"', type: 'property', detail: 'SVG Text Anchor' },
    { label: 'title', value: 'title="$0"', type: 'property', detail: 'Tooltip' },
    { label: 'transform', value: 'transform="$0"', type: 'property', detail: 'SVG Transform' },
    { label: 'translate', value: 'translate="no"', type: 'property', detail: 'Translate' },
    { label: 'type', value: 'type="$0"', type: 'property', detail: 'Input/Mime Type' },
    { label: 'usemap', value: 'usemap="#$0"', type: 'property', detail: 'Use Map' },
    { label: 'value', value: 'value="$0"', type: 'property', detail: 'Input Value' },
    { label: 'version', value: 'version="1.1"', type: 'property', detail: 'SVG Version' },
    { label: 'viewBox', value: 'viewBox="0 0 100 100"', type: 'property', detail: 'SVG ViewBox' },
    { label: 'width', value: 'width="$0"', type: 'property', detail: 'Width' },
    { label: 'wrap', value: 'wrap="hard"', type: 'property', detail: 'Textarea Wrap' },
    { label: 'x', value: 'x="0"', type: 'property', detail: 'SVG X' },
    { label: 'x1', value: 'x1="0"', type: 'property', detail: 'SVG X1' },
    { label: 'x2', value: 'x2="100"', type: 'property', detail: 'SVG X2' },
    { label: 'xmlns', value: 'xmlns="http://www.w3.org/2000/svg"', type: 'property', detail: 'XML Namespace' },
    { label: 'y', value: 'y="0"', type: 'property', detail: 'SVG Y' },
    { label: 'y1', value: 'y1="0"', type: 'property', detail: 'SVG Y1' },
    { label: 'y2', value: 'y2="100"', type: 'property', detail: 'SVG Y2' },
];

export const HTML_TAGS: Suggestion[] = [
  { label: '!', value: '<!DOCTYPE html>\n<html lang="en">\n<head>\n\t<meta charset="UTF-8" />\n\t<meta name="viewport" content="width=device-width, initial-scale=1.0" />\n\t<title>Document</title>\n</head>\n<body>\n\t$0\n</body>\n</html>', type: 'snippet', detail: 'HTML5 Boilerplate' },
  { label: 'a', value: '<a href="$0"></a>', type: 'tag', detail: 'Anchor' },
  { label: 'a:blank', value: '<a href="$0" target="_blank" rel="noopener noreferrer"></a>', type: 'snippet', detail: 'New Tab Link' },
  { label: 'a:link', value: '<a href="http://$0"></a>', type: 'snippet', detail: 'External Link' },
  { label: 'a:mail', value: '<a href="mailto:$0"></a>', type: 'snippet', detail: 'Mail Link' },
  { label: 'a:tel', value: '<a href="tel:$0"></a>', type: 'snippet', detail: 'Phone Link' },
  { label: 'abbr', value: '<abbr title="$0"></abbr>', type: 'tag', detail: 'Abbreviation' },
  { label: 'address', value: '<address>$0</address>', type: 'tag', detail: 'Address' },
  { label: 'animate', value: '<animate attributeName="" values="" dur="" repeatCount="" />', type: 'tag', detail: 'SVG Animate' },
  { label: 'animateMotion', value: '<animateMotion dur="" repeatCount="">\n\t<mpath href="" />\n</animateMotion>', type: 'tag', detail: 'SVG Animate Motion' },
  { label: 'animateTransform', value: '<animateTransform attributeName="transform" type="" from="" to="" dur="" repeatCount="" />', type: 'tag', detail: 'SVG Animate Transform' },
  { label: 'area', value: '<area shape="" coords="" href="" alt="" />', type: 'tag', detail: 'Area' },
  { label: 'article', value: '<article>$0</article>', type: 'tag', detail: 'Article' },
  { label: 'aside', value: '<aside>$0</aside>', type: 'tag', detail: 'Aside' },
  { label: 'audio', value: '<audio src="$0" controls></audio>', type: 'tag', detail: 'Audio' },
  { label: 'b', value: '<b>$0</b>', type: 'tag', detail: 'Bold' },
  { label: 'base', value: '<base href="$0" />', type: 'tag', detail: 'Base' },
  { label: 'bdi', value: '<bdi>$0</bdi>', type: 'tag', detail: 'BDI' },
  { label: 'bdo', value: '<bdo dir="">$0</bdo>', type: 'tag', detail: 'BDO' },
  { label: 'blockquote', value: '<blockquote>$0</blockquote>', type: 'tag', detail: 'Blockquote' },
  { label: 'body', value: '<body>\n\t$0\n</body>', type: 'tag', detail: 'Body' },
  { label: 'br', value: '<br />', type: 'tag', detail: 'Break' },
  { label: 'button', value: '<button type="button">$0</button>', type: 'tag', detail: 'Button' },
  { label: 'button:submit', value: '<button type="submit">$0</button>', type: 'snippet', detail: 'Submit Button' },
  { label: 'canvas', value: '<canvas id="$0" width="300" height="150"></canvas>', type: 'tag', detail: 'Canvas' },
  { label: 'caption', value: '<caption>$0</caption>', type: 'tag', detail: 'Caption' },
  { label: 'circle', value: '<circle cx="50" cy="50" r="40" fill="currentColor" />', type: 'tag', detail: 'SVG Circle' },
  { label: 'cite', value: '<cite>$0</cite>', type: 'tag', detail: 'Cite' },
  { label: 'clipPath', value: '<clipPath id="">$0</clipPath>', type: 'tag', detail: 'SVG ClipPath' },
  { label: 'code', value: '<code>$0</code>', type: 'tag', detail: 'Code' },
  { label: 'col', value: '<col span="" class="" />', type: 'tag', detail: 'Column' },
  { label: 'colgroup', value: '<colgroup>\n\t<col />\n</colgroup>', type: 'tag', detail: 'Column Group' },
  { label: 'data', value: '<data value="">$0</data>', type: 'tag', detail: 'Data' },
  { label: 'datalist', value: '<datalist id="">\n\t<option value="">\n</datalist>', type: 'tag', detail: 'Datalist' },
  { label: 'dd', value: '<dd>$0</dd>', type: 'tag', detail: 'Description Details' },
  { label: 'defs', value: '<defs>\n\t$0\n</defs>', type: 'tag', detail: 'SVG Defs' },
  { label: 'del', value: '<del>$0</del>', type: 'tag', detail: 'Deleted' },
  { label: 'desc', value: '<desc>$0</desc>', type: 'tag', detail: 'SVG Desc' },
  { label: 'details', value: '<details>\n\t<summary>Title</summary>\n\t$0\n</details>', type: 'tag', detail: 'Details' },
  { label: 'dfn', value: '<dfn>$0</dfn>', type: 'tag', detail: 'Definition' },
  { label: 'dialog', value: '<dialog open>$0</dialog>', type: 'tag', detail: 'Dialog' },
  { label: 'div', value: '<div>$0</div>', type: 'tag', detail: 'Div' },
  { label: 'dl', value: '<dl>\n\t<dt></dt>\n\t<dd></dd>\n</dl>', type: 'tag', detail: 'Description List' },
  { label: 'dl+', value: '<dl>\n\t<dt>$0</dt>\n\t<dd></dd>\n</dl>', type: 'snippet', detail: 'DL Structure' },
  { label: 'dt', value: '<dt>$0</dt>', type: 'tag', detail: 'Description Term' },
  { label: 'ellipse', value: '<ellipse cx="100" cy="50" rx="100" ry="50" />', type: 'tag', detail: 'SVG Ellipse' },
  { label: 'em', value: '<em>$0</em>', type: 'tag', detail: 'Emphasis' },
  { label: 'embed', value: '<embed src="$0" type="" />', type: 'tag', detail: 'Embed' },
  { label: 'feBlend', value: '<feBlend in="" in2="" mode="" />', type: 'tag', detail: 'SVG Filter Blend' },
  { label: 'feColorMatrix', value: '<feColorMatrix type="matrix" values="" />', type: 'tag', detail: 'SVG Filter Matrix' },
  { label: 'feGaussianBlur', value: '<feGaussianBlur in="" stdDeviation="" />', type: 'tag', detail: 'SVG Filter Blur' },
  { label: 'fieldset', value: '<fieldset>\n\t<legend>$0</legend>\n</fieldset>', type: 'tag', detail: 'Fieldset' },
  { label: 'figcaption', value: '<figcaption>$0</figcaption>', type: 'tag', detail: 'Figure Caption' },
  { label: 'figure', value: '<figure>\n\t<img src="" alt="" />\n\t<figcaption>$0</figcaption>\n</figure>', type: 'tag', detail: 'Figure' },
  { label: 'filter', value: '<filter id="">\n\t$0\n</filter>', type: 'tag', detail: 'SVG Filter' },
  { label: 'footer', value: '<footer>$0</footer>', type: 'tag', detail: 'Footer' },
  { label: 'foreignObject', value: '<foreignObject x="" y="" width="" height="">\n\t$0\n</foreignObject>', type: 'tag', detail: 'SVG ForeignObject' },
  { label: 'form', value: '<form action="$0" method="POST"></form>', type: 'tag', detail: 'Form' },
  { label: 'form:get', value: '<form action="$0" method="get"></form>', type: 'snippet', detail: 'GET Form' },
  { label: 'form:post', value: '<form action="$0" method="post"></form>', type: 'snippet', detail: 'POST Form' },
  { label: 'g', value: '<g>\n\t$0\n</g>', type: 'tag', detail: 'SVG Group' },
  { label: 'h1', value: '<h1>$0</h1>', type: 'tag', detail: 'Heading 1' },
  { label: 'h2', value: '<h2>$0</h2>', type: 'tag', detail: 'Heading 2' },
  { label: 'h3', value: '<h3>$0</h3>', type: 'tag', detail: 'Heading 3' },
  { label: 'h4', value: '<h4>$0</h4>', type: 'tag', detail: 'Heading 4' },
  { label: 'h5', value: '<h5>$0</h5>', type: 'tag', detail: 'Heading 5' },
  { label: 'h6', value: '<h6>$0</h6>', type: 'tag', detail: 'Heading 6' },
  { label: 'head', value: '<head>\n\t$0\n</head>', type: 'tag', detail: 'Head' },
  { label: 'header', value: '<header>$0</header>', type: 'tag', detail: 'Header' },
  { label: 'hgroup', value: '<hgroup>\n\t<h1></h1>\n\t<h2></h2>\n</hgroup>', type: 'tag', detail: 'Heading Group' },
  { label: 'hr', value: '<hr />', type: 'tag', detail: 'Horizontal Rule' },
  { label: 'html', value: '<html lang="en">\n$0\n</html>', type: 'tag', detail: 'HTML' },
  { label: 'i', value: '<i>$0</i>', type: 'tag', detail: 'Italic' },
  { label: 'iframe', value: '<iframe src="$0" frameborder="0"></iframe>', type: 'tag', detail: 'Iframe' },
  { label: 'image', value: '<image href="" x="" y="" width="" height="" />', type: 'tag', detail: 'SVG Image' },
  { label: 'img', value: '<img src="$0" alt="" />', type: 'tag', detail: 'Image' },
  { label: 'input', value: '<input type="text" />', type: 'tag', detail: 'Input' },
  { label: 'input:button', value: '<input type="button" value="$0" />', type: 'snippet', detail: 'Input Button' },
  { label: 'input:checkbox', value: '<input type="checkbox" name="$0" id="" />', type: 'snippet', detail: 'Input Checkbox' },
  { label: 'input:color', value: '<input type="color" name="$0" id="" />', type: 'snippet', detail: 'Input Color' },
  { label: 'input:date', value: '<input type="date" name="$0" id="" />', type: 'snippet', detail: 'Input Date' },
  { label: 'input:email', value: '<input type="email" name="$0" id="" />', type: 'snippet', detail: 'Input Email' },
  { label: 'input:file', value: '<input type="file" name="$0" id="" />', type: 'snippet', detail: 'Input File' },
  { label: 'input:hidden', value: '<input type="hidden" name="$0" />', type: 'snippet', detail: 'Input Hidden' },
  { label: 'input:number', value: '<input type="number" name="$0" id="" />', type: 'snippet', detail: 'Input Number' },
  { label: 'input:password', value: '<input type="password" name="$0" id="" />', type: 'snippet', detail: 'Input Password' },
  { label: 'input:radio', value: '<input type="radio" name="$0" id="" />', type: 'snippet', detail: 'Input Radio' },
  { label: 'input:range', value: '<input type="range" name="$0" id="" />', type: 'snippet', detail: 'Input Range' },
  { label: 'input:search', value: '<input type="search" name="$0" id="" />', type: 'snippet', detail: 'Input Search' },
  { label: 'input:submit', value: '<input type="submit" value="$0" />', type: 'snippet', detail: 'Input Submit' },
  { label: 'input:tel', value: '<input type="tel" name="$0" id="" />', type: 'snippet', detail: 'Input Tel' },
  { label: 'input:text', value: '<input type="text" name="$0" id="" />', type: 'snippet', detail: 'Input Text' },
  { label: 'input:url', value: '<input type="url" name="$0" id="" />', type: 'snippet', detail: 'Input URL' },
  { label: 'ins', value: '<ins>$0</ins>', type: 'tag', detail: 'Inserted' },
  { label: 'kbd', value: '<kbd>$0</kbd>', type: 'tag', detail: 'Keyboard' },
  { label: 'label', value: '<label for="$0"></label>', type: 'tag', detail: 'Label' },
  { label: 'legend', value: '<legend>$0</legend>', type: 'tag', detail: 'Legend' },
  { label: 'li', value: '<li>$0</li>', type: 'tag', detail: 'List Item' },
  { label: 'line', value: '<line x1="" y1="" x2="" y2="" stroke="" />', type: 'tag', detail: 'SVG Line' },
  { label: 'linearGradient', value: '<linearGradient id="">\n\t<stop offset="0%" stop-color="" />\n\t<stop offset="100%" stop-color="" />\n</linearGradient>', type: 'tag', detail: 'SVG Linear Gradient' },
  { label: 'link', value: '<link rel="stylesheet" href="$0" />', type: 'tag', detail: 'Link' },
  { label: 'link:css', value: '<link rel="stylesheet" href="style.css" />', type: 'snippet', detail: 'CSS Link' },
  { label: 'link:favicon', value: '<link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />', type: 'snippet', detail: 'Favicon' },
  { label: 'main', value: '<main>$0</main>', type: 'tag', detail: 'Main' },
  { label: 'map', value: '<map name="">$0</map>', type: 'tag', detail: 'Map' },
  { label: 'mark', value: '<mark>$0</mark>', type: 'tag', detail: 'Mark' },
  { label: 'marker', value: '<marker id="" markerWidth="" markerHeight="" refX="" refY="" orient="auto">\n\t$0\n</marker>', type: 'tag', detail: 'SVG Marker' },
  { label: 'mask', value: '<mask id="">\n\t$0\n</mask>', type: 'tag', detail: 'SVG Mask' },
  { label: 'math', value: '<math xmlns="http://www.w3.org/1998/Math/MathML">\n\t$0\n</math>', type: 'tag', detail: 'MathML' },
  { label: 'menu', value: '<menu>\n\t<li><button>$0</button></li>\n</menu>', type: 'tag', detail: 'Menu' },
  { label: 'meta', value: '<meta name="$0" content="" />', type: 'tag', detail: 'Meta' },
  { label: 'meta:utf', value: '<meta charset="UTF-8" />', type: 'snippet', detail: 'Meta UTF-8' },
  { label: 'meta:vp', value: '<meta name="viewport" content="width=device-width, initial-scale=1.0" />', type: 'snippet', detail: 'Meta Viewport' },
  { label: 'meter', value: '<meter value="" min="" max="">$0</meter>', type: 'tag', detail: 'Meter' },
  { label: 'nav', value: '<nav>$0</nav>', type: 'tag', detail: 'Nav' },
  { label: 'noscript', value: '<noscript>$0</noscript>', type: 'tag', detail: 'Noscript' },
  { label: 'object', value: '<object data="" type="">$0</object>', type: 'tag', detail: 'Object' },
  { label: 'ol', value: '<ol>\n\t<li>$0</li>\n</ol>', type: 'tag', detail: 'Ordered List' },
  { label: 'ol+', value: '<ol>\n\t<li>$0</li>\n</ol>', type: 'snippet', detail: 'OL Structure' },
  { label: 'optgroup', value: '<optgroup label="">$0</optgroup>', type: 'tag', detail: 'Optgroup' },
  { label: 'option', value: '<option value="$0"></option>', type: 'tag', detail: 'Option' },
  { label: 'output', value: '<output name="">$0</output>', type: 'tag', detail: 'Output' },
  { label: 'p', value: '<p>$0</p>', type: 'tag', detail: 'Paragraph' },
  { label: 'param', value: '<param name="" value="" />', type: 'tag', detail: 'Param' },
  { label: 'path', value: '<path d="$0" />', type: 'tag', detail: 'SVG Path' },
  { label: 'pattern', value: '<pattern id="" width="" height="" patternUnits="userSpaceOnUse">\n\t$0\n</pattern>', type: 'tag', detail: 'SVG Pattern' },
  { label: 'picture', value: '<picture>\n\t<source srcset="" type="" />\n\t<img src="" alt="" />\n</picture>', type: 'tag', detail: 'Picture' },
  { label: 'polygon', value: '<polygon points="" />', type: 'tag', detail: 'SVG Polygon' },
  { label: 'polyline', value: '<polyline points="" />', type: 'tag', detail: 'SVG Polyline' },
  { label: 'pre', value: '<pre>$0</pre>', type: 'tag', detail: 'Pre' },
  { label: 'progress', value: '<progress value="" max="">$0</progress>', type: 'tag', detail: 'Progress' },
  { label: 'q', value: '<q>$0</q>', type: 'tag', detail: 'Quote' },
  { label: 'radialGradient', value: '<radialGradient id="">\n\t<stop offset="" stop-color="" />\n</radialGradient>', type: 'tag', detail: 'SVG Radial Gradient' },
  { label: 'rect', value: '<rect x="" y="" width="" height="" />', type: 'tag', detail: 'SVG Rect' },
  { label: 'rp', value: '<rp>$0</rp>', type: 'tag', detail: 'Ruby Paren' },
  { label: 'rt', value: '<rt>$0</rt>', type: 'tag', detail: 'Ruby Text' },
  { label: 'ruby', value: '<ruby>$0</ruby>', type: 'tag', detail: 'Ruby' },
  { label: 's', value: '<s>$0</s>', type: 'tag', detail: 'Strikethrough' },
  { label: 'samp', value: '<samp>$0</samp>', type: 'tag', detail: 'Sample' },
  { label: 'script', value: '<script>\n\t$0\n</script>', type: 'tag', detail: 'Script' },
  { label: 'script:module', value: '<script type="module" src="$0"></script>', type: 'snippet', detail: 'Module Script' },
  { label: 'script:src', value: '<script src="$0"></script>', type: 'snippet', detail: 'External Script' },
  { label: 'section', value: '<section>$0</section>', type: 'tag', detail: 'Section' },
  { label: 'select', value: '<select name="$0" id=""></select>', type: 'tag', detail: 'Select' },
  { label: 'small', value: '<small>$0</small>', type: 'tag', detail: 'Small' },
  { label: 'source', value: '<source src="$0" type="video/mp4" />', type: 'tag', detail: 'Source' },
  { label: 'span', value: '<span>$0</span>', type: 'tag', detail: 'Span' },
  { label: 'stop', value: '<stop offset="" stop-color="" />', type: 'tag', detail: 'SVG Stop' },
  { label: 'strong', value: '<strong>$0</strong>', type: 'tag', detail: 'Strong' },
  { label: 'style', value: '<style>\n\t$0\n</style>', type: 'tag', detail: 'Style' },
  { label: 'sub', value: '<sub>$0</sub>', type: 'tag', detail: 'Subscript' },
  { label: 'summary', value: '<summary>$0</summary>', type: 'tag', detail: 'Summary' },
  { label: 'sup', value: '<sup>$0</sup>', type: 'tag', detail: 'Superscript' },
  { label: 'svg', value: '<svg width="100" height="100" viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">\n\t$0\n</svg>', type: 'tag', detail: 'SVG Root' },
  { label: 'switch', value: '<switch>\n\t$0\n</switch>', type: 'tag', detail: 'SVG Switch' },
  { label: 'symbol', value: '<symbol id="" viewBox="">\n\t$0\n</symbol>', type: 'tag', detail: 'SVG Symbol' },
  { label: 'table', value: '<table>\n\t<thead>\n\t\t<tr>\n\t\t\t<th>$0</th>\n\t\t</tr>\n\t</thead>\n\t<tbody>\n\t\t<tr>\n\t\t\t<td></td>\n\t\t</tr>\n\t</tbody>\n</table>', type: 'tag', detail: 'Table' },
  { label: 'table+', value: '<table>\n\t<thead>\n\t\t<tr>\n\t\t\t<th>$0</th>\n\t\t</tr>\n\t</thead>\n\t<tbody>\n\t\t<tr>\n\t\t\t<td></td>\n\t\t</tr>\n\t</tbody>\n</table>', type: 'snippet', detail: 'Table Structure' },
  { label: 'tbody', value: '<tbody>$0</tbody>', type: 'tag', detail: 'Table Body' },
  { label: 'td', value: '<td>$0</td>', type: 'tag', detail: 'Table Cell' },
  { label: 'template', value: '<template>\n\t$0\n</template>', type: 'tag', detail: 'Template' },
  { label: 'text', value: '<text x="" y="">$0</text>', type: 'tag', detail: 'SVG Text' },
  { label: 'textarea', value: '<textarea name="$0" id="" cols="30" rows="10"></textarea>', type: 'tag', detail: 'Textarea' },
  { label: 'textPath', value: '<textPath href="">$0</textPath>', type: 'tag', detail: 'SVG TextPath' },
  { label: 'tfoot', value: '<tfoot>$0</tfoot>', type: 'tag', detail: 'Table Footer' },
  { label: 'th', value: '<th>$0</th>', type: 'tag', detail: 'Table Header' },
  { label: 'thead', value: '<thead>$0</thead>', type: 'tag', detail: 'Table Head' },
  { label: 'time', value: '<time datetime="">$0</time>', type: 'tag', detail: 'Time' },
  { label: 'title', value: '<title>$0</title>', type: 'tag', detail: 'Title' },
  { label: 'tr', value: '<tr>$0</tr>', type: 'tag', detail: 'Table Row' },
  { label: 'track', value: '<track src="" kind="" srclang="" label="" />', type: 'tag', detail: 'Track' },
  { label: 'tspan', value: '<tspan>$0</tspan>', type: 'tag', detail: 'SVG TSpan' },
  { label: 'u', value: '<u>$0</u>', type: 'tag', detail: 'Underline' },
  { label: 'ul', value: '<ul>\n\t<li>$0</li>\n</ul>', type: 'tag', detail: 'Unordered List' },
  { label: 'ul+', value: '<ul>\n\t<li>$0</li>\n</ul>', type: 'snippet', detail: 'UL Structure' },
  { label: 'use', value: '<use href="" />', type: 'tag', detail: 'SVG Use' },
  { label: 'var', value: '<var>$0</var>', type: 'tag', detail: 'Variable' },
  { label: 'video', value: '<video src="$0" controls></video>', type: 'tag', detail: 'Video' },
  { label: 'view', value: '<view id="" viewBox="" />', type: 'tag', detail: 'SVG View' },
  { label: 'wbr', value: '<wbr />', type: 'tag', detail: 'Word Break' },
];

export const CSS_PROPS: Suggestion[] = [
    { label: 'accent-color', value: 'accent-color: #007acc;', type: 'property', detail: 'Accent Color' },
    { label: 'align-content', value: 'align-content: center;', type: 'property', detail: 'Align Content' },
    { label: 'align-items', value: 'align-items: center;', type: 'property', detail: 'Align Items' },
    { label: 'align-self', value: 'align-self: auto;', type: 'property', detail: 'Align Self' },
    { label: 'all', value: 'all: unset;', type: 'property', detail: 'Reset All' },
    { label: 'animation', value: 'animation: name 1s ease infinite;', type: 'property', detail: 'Animation' },
    { label: 'animation-delay', value: 'animation-delay: 0s;', type: 'property', detail: 'Anim Delay' },
    { label: 'animation-direction', value: 'animation-direction: alternate;', type: 'property', detail: 'Anim Direction' },
    { label: 'animation-duration', value: 'animation-duration: 1s;', type: 'property', detail: 'Anim Duration' },
    { label: 'animation-fill-mode', value: 'animation-fill-mode: forwards;', type: 'property', detail: 'Anim Fill' },
    { label: 'animation-iteration-count', value: 'animation-iteration-count: infinite;', type: 'property', detail: 'Anim Count' },
    { label: 'animation-name', value: 'animation-name: none;', type: 'property', detail: 'Anim Name' },
    { label: 'animation-play-state', value: 'animation-play-state: running;', type: 'property', detail: 'Anim State' },
    { label: 'animation-timing-function', value: 'animation-timing-function: ease;', type: 'property', detail: 'Anim Timing' },
    { label: 'aspect-ratio', value: 'aspect-ratio: 16/9;', type: 'property', detail: 'Aspect Ratio' },
    { label: 'backdrop-filter', value: 'backdrop-filter: blur(10px);', type: 'property', detail: 'Backdrop Filter' },
    { label: 'backface-visibility', value: 'backface-visibility: hidden;', type: 'property', detail: 'Backface Visibility' },
    { label: 'background', value: 'background: #fff;', type: 'property', detail: 'Background' },
    { label: 'background-attachment', value: 'background-attachment: fixed;', type: 'property', detail: 'BG Attachment' },
    { label: 'background-blend-mode', value: 'background-blend-mode: multiply;', type: 'property', detail: 'BG Blend' },
    { label: 'background-clip', value: 'background-clip: border-box;', type: 'property', detail: 'BG Clip' },
    { label: 'background-color', value: 'background-color: transparent;', type: 'property', detail: 'BG Color' },
    { label: 'background-image', value: 'background-image: url();', type: 'property', detail: 'BG Image' },
    { label: 'background-origin', value: 'background-origin: border-box;', type: 'property', detail: 'BG Origin' },
    { label: 'background-position', value: 'background-position: center;', type: 'property', detail: 'BG Position' },
    { label: 'background-repeat', value: 'background-repeat: no-repeat;', type: 'property', detail: 'BG Repeat' },
    { label: 'background-size', value: 'background-size: cover;', type: 'property', detail: 'BG Size' },
    { label: 'border', value: 'border: 1px solid #000;', type: 'property', detail: 'Border' },
    { label: 'border-bottom', value: 'border-bottom: 1px solid #000;', type: 'property', detail: 'Border Bottom' },
    { label: 'border-collapse', value: 'border-collapse: collapse;', type: 'property', detail: 'Border Collapse' },
    { label: 'border-color', value: 'border-color: #000;', type: 'property', detail: 'Border Color' },
    { label: 'border-image', value: 'border-image: url() 30 round;', type: 'property', detail: 'Border Image' },
    { label: 'border-left', value: 'border-left: 1px solid #000;', type: 'property', detail: 'Border Left' },
    { label: 'border-radius', value: 'border-radius: 4px;', type: 'property', detail: 'Border Radius' },
    { label: 'border-right', value: 'border-right: 1px solid #000;', type: 'property', detail: 'Border Right' },
    { label: 'border-spacing', value: 'border-spacing: 0;', type: 'property', detail: 'Border Spacing' },
    { label: 'border-style', value: 'border-style: solid;', type: 'property', detail: 'Border Style' },
    { label: 'border-top', value: 'border-top: 1px solid #000;', type: 'property', detail: 'Border Top' },
    { label: 'border-width', value: 'border-width: 1px;', type: 'property', detail: 'Border Width' },
    { label: 'bottom', value: 'bottom: 0;', type: 'property', detail: 'Bottom' },
    { label: 'box-shadow', value: 'box-shadow: 0 4px 6px rgba(0,0,0,0.1);', type: 'property', detail: 'Box Shadow' },
    { label: 'box-sizing', value: 'box-sizing: border-box;', type: 'property', detail: 'Box Sizing' },
    { label: 'break-after', value: 'break-after: always;', type: 'property', detail: 'Break After' },
    { label: 'break-before', value: 'break-before: always;', type: 'property', detail: 'Break Before' },
    { label: 'break-inside', value: 'break-inside: avoid;', type: 'property', detail: 'Break Inside' },
    { label: 'caption-side', value: 'caption-side: bottom;', type: 'property', detail: 'Caption Side' },
    { label: 'caret-color', value: 'caret-color: auto;', type: 'property', detail: 'Caret Color' },
    { label: 'clear', value: 'clear: both;', type: 'property', detail: 'Clear' },
    { label: 'clip-path', value: 'clip-path: circle(50%);', type: 'property', detail: 'Clip Path' },
    { label: 'color', value: 'color: #000;', type: 'property', detail: 'Color' },
    { label: 'column-count', value: 'column-count: 2;', type: 'property', detail: 'Column Count' },
    { label: 'column-fill', value: 'column-fill: balance;', type: 'property', detail: 'Column Fill' },
    { label: 'column-gap', value: 'column-gap: 1rem;', type: 'property', detail: 'Column Gap' },
    { label: 'column-rule', value: 'column-rule: 1px solid #000;', type: 'property', detail: 'Column Rule' },
    { label: 'column-span', value: 'column-span: all;', type: 'property', detail: 'Column Span' },
    { label: 'column-width', value: 'column-width: 100px;', type: 'property', detail: 'Column Width' },
    { label: 'columns', value: 'columns: 2 100px;', type: 'property', detail: 'Columns' },
    { label: 'content', value: 'content: "";', type: 'property', detail: 'Content' },
    { label: 'counter-increment', value: 'counter-increment: section;', type: 'property', detail: 'Counter Inc' },
    { label: 'counter-reset', value: 'counter-reset: section;', type: 'property', detail: 'Counter Reset' },
    { label: 'cursor', value: 'cursor: pointer;', type: 'property', detail: 'Cursor' },
    { label: 'direction', value: 'direction: ltr;', type: 'property', detail: 'Direction' },
    { label: 'display', value: 'display: flex;', type: 'property', detail: 'Display' },
    { label: 'empty-cells', value: 'empty-cells: show;', type: 'property', detail: 'Empty Cells' },
    { label: 'filter', value: 'filter: blur(5px);', type: 'property', detail: 'Filter' },
    { label: 'flex', value: 'flex: 1;', type: 'property', detail: 'Flex' },
    { label: 'flex-basis', value: 'flex-basis: auto;', type: 'property', detail: 'Flex Basis' },
    { label: 'flex-direction', value: 'flex-direction: row;', type: 'property', detail: 'Flex Direction' },
    { label: 'flex-flow', value: 'flex-flow: row wrap;', type: 'property', detail: 'Flex Flow' },
    { label: 'flex-grow', value: 'flex-grow: 1;', type: 'property', detail: 'Flex Grow' },
    { label: 'flex-shrink', value: 'flex-shrink: 1;', type: 'property', detail: 'Flex Shrink' },
    { label: 'flex-wrap', value: 'flex-wrap: wrap;', type: 'property', detail: 'Flex Wrap' },
    { label: 'float', value: 'float: left;', type: 'property', detail: 'Float' },
    { label: 'font', value: 'font: 16px sans-serif;', type: 'property', detail: 'Font' },
    { label: 'font-family', value: 'font-family: sans-serif;', type: 'property', detail: 'Font Family' },
    { label: 'font-size', value: 'font-size: 1rem;', type: 'property', detail: 'Font Size' },
    { label: 'font-style', value: 'font-style: italic;', type: 'property', detail: 'Font Style' },
    { label: 'font-variant', value: 'font-variant: small-caps;', type: 'property', detail: 'Font Variant' },
    { label: 'font-weight', value: 'font-weight: bold;', type: 'property', detail: 'Font Weight' },
    { label: 'gap', value: 'gap: 1rem;', type: 'property', detail: 'Gap' },
    { label: 'grid', value: 'grid: auto / auto;', type: 'property', detail: 'Grid' },
    { label: 'grid-area', value: 'grid-area: 1 / 1 / 2 / 2;', type: 'property', detail: 'Grid Area' },
    { label: 'grid-auto-columns', value: 'grid-auto-columns: auto;', type: 'property', detail: 'Grid Auto Cols' },
    { label: 'grid-auto-flow', value: 'grid-auto-flow: row;', type: 'property', detail: 'Grid Auto Flow' },
    { label: 'grid-auto-rows', value: 'grid-auto-rows: auto;', type: 'property', detail: 'Grid Auto Rows' },
    { label: 'grid-column', value: 'grid-column: 1 / 3;', type: 'property', detail: 'Grid Column' },
    { label: 'grid-column-end', value: 'grid-column-end: 3;', type: 'property', detail: 'Grid Col End' },
    { label: 'grid-column-start', value: 'grid-column-start: 1;', type: 'property', detail: 'Grid Col Start' },
    { label: 'grid-row', value: 'grid-row: 1 / 2;', type: 'property', detail: 'Grid Row' },
    { label: 'grid-row-end', value: 'grid-row-end: 2;', type: 'property', detail: 'Grid Row End' },
    { label: 'grid-row-start', value: 'grid-row-start: 1;', type: 'property', detail: 'Grid Row Start' },
    { label: 'grid-template', value: 'grid-template: none;', type: 'property', detail: 'Grid Template' },
    { label: 'grid-template-areas', value: 'grid-template-areas: "header header";', type: 'property', detail: 'Grid Areas' },
    { label: 'grid-template-columns', value: 'grid-template-columns: 1fr 1fr;', type: 'property', detail: 'Grid Cols' },
    { label: 'grid-template-rows', value: 'grid-template-rows: auto;', type: 'property', detail: 'Grid Rows' },
    { label: 'height', value: 'height: 100vh;', type: 'property', detail: 'Height' },
    { label: 'hyphens', value: 'hyphens: auto;', type: 'property', detail: 'Hyphens' },
    { label: 'isolation', value: 'isolation: isolate;', type: 'property', detail: 'Isolation' },
    { label: 'justify-content', value: 'justify-content: center;', type: 'property', detail: 'Justify Content' },
    { label: 'justify-items', value: 'justify-items: center;', type: 'property', detail: 'Justify Items' },
    { label: 'justify-self', value: 'justify-self: center;', type: 'property', detail: 'Justify Self' },
    { label: 'left', value: 'left: 0;', type: 'property', detail: 'Left' },
    { label: 'letter-spacing', value: 'letter-spacing: 1px;', type: 'property', detail: 'Letter Spacing' },
    { label: 'line-height', value: 'line-height: 1.5;', type: 'property', detail: 'Line Height' },
    { label: 'list-style', value: 'list-style: none;', type: 'property', detail: 'List Style' },
    { label: 'margin', value: 'margin: 0;', type: 'property', detail: 'Margin' },
    { label: 'margin-bottom', value: 'margin-bottom: 0;', type: 'property', detail: 'Margin Bottom' },
    { label: 'margin-left', value: 'margin-left: 0;', type: 'property', detail: 'Margin Left' },
    { label: 'margin-right', value: 'margin-right: 0;', type: 'property', detail: 'Margin Right' },
    { label: 'margin-top', value: 'margin-top: 0;', type: 'property', detail: 'Margin Top' },
    { label: 'mask', value: 'mask: url();', type: 'property', detail: 'Mask' },
    { label: 'max-height', value: 'max-height: 100vh;', type: 'property', detail: 'Max Height' },
    { label: 'max-width', value: 'max-width: 100%;', type: 'property', detail: 'Max Width' },
    { label: 'min-height', value: 'min-height: 0;', type: 'property', detail: 'Min Height' },
    { label: 'min-width', value: 'min-width: 0;', type: 'property', detail: 'Min Width' },
    { label: 'mix-blend-mode', value: 'mix-blend-mode: multiply;', type: 'property', detail: 'Mix Blend' },
    { label: 'object-fit', value: 'object-fit: cover;', type: 'property', detail: 'Object Fit' },
    { label: 'object-position', value: 'object-position: center;', type: 'property', detail: 'Object Pos' },
    { label: 'opacity', value: 'opacity: 0.5;', type: 'property', detail: 'Opacity' },
    { label: 'order', value: 'order: 1;', type: 'property', detail: 'Order' },
    { label: 'outline', value: 'outline: 1px solid #000;', type: 'property', detail: 'Outline' },
    { label: 'outline-offset', value: 'outline-offset: 2px;', type: 'property', detail: 'Outline Offset' },
    { label: 'overflow', value: 'overflow: hidden;', type: 'property', detail: 'Overflow' },
    { label: 'overflow-x', value: 'overflow-x: auto;', type: 'property', detail: 'Overflow X' },
    { label: 'overflow-y', value: 'overflow-y: scroll;', type: 'property', detail: 'Overflow Y' },
    { label: 'padding', value: 'padding: 1rem;', type: 'property', detail: 'Padding' },
    { label: 'padding-bottom', value: 'padding-bottom: 1rem;', type: 'property', detail: 'Padding Bottom' },
    { label: 'padding-left', value: 'padding-left: 1rem;', type: 'property', detail: 'Padding Left' },
    { label: 'padding-right', value: 'padding-right: 1rem;', type: 'property', detail: 'Padding Right' },
    { label: 'padding-top', value: 'padding-top: 1rem;', type: 'property', detail: 'Padding Top' },
    { label: 'perspective', value: 'perspective: 1000px;', type: 'property', detail: 'Perspective' },
    { label: 'perspective-origin', value: 'perspective-origin: center;', type: 'property', detail: 'Perspective Origin' },
    { label: 'place-content', value: 'place-content: center;', type: 'property', detail: 'Place Content' },
    { label: 'place-items', value: 'place-items: center;', type: 'property', detail: 'Place Items' },
    { label: 'place-self', value: 'place-self: center;', type: 'property', detail: 'Place Self' },
    { label: 'pointer-events', value: 'pointer-events: none;', type: 'property', detail: 'Pointer Events' },
    { label: 'position', value: 'position: absolute;', type: 'property', detail: 'Position' },
    { label: 'quotes', value: 'quotes: "“" "”";', type: 'property', detail: 'Quotes' },
    { label: 'resize', value: 'resize: both;', type: 'property', detail: 'Resize' },
    { label: 'right', value: 'right: 0;', type: 'property', detail: 'Right' },
    { label: 'row-gap', value: 'row-gap: 1rem;', type: 'property', detail: 'Row Gap' },
    { label: 'scroll-behavior', value: 'scroll-behavior: smooth;', type: 'property', detail: 'Scroll Behavior' },
    { label: 'scroll-padding', value: 'scroll-padding: 1rem;', type: 'property', detail: 'Scroll Padding' },
    { label: 'scroll-snap-align', value: 'scroll-snap-align: start;', type: 'property', detail: 'Scroll Snap Align' },
    { label: 'scroll-snap-type', value: 'scroll-snap-type: x mandatory;', type: 'property', detail: 'Scroll Snap Type' },
    { label: 'table-layout', value: 'table-layout: fixed;', type: 'property', detail: 'Table Layout' },
    { label: 'text-align', value: 'text-align: center;', type: 'property', detail: 'Text Align' },
    { label: 'text-decoration', value: 'text-decoration: none;', type: 'property', detail: 'Text Decoration' },
    { label: 'text-indent', value: 'text-indent: 1rem;', type: 'property', detail: 'Text Indent' },
    { label: 'text-overflow', value: 'text-overflow: ellipsis;', type: 'property', detail: 'Text Overflow' },
    { label: 'text-shadow', value: 'text-shadow: 1px 1px 2px #000;', type: 'property', detail: 'Text Shadow' },
    { label: 'text-transform', value: 'text-transform: uppercase;', type: 'property', detail: 'Text Transform' },
    { label: 'top', value: 'top: 0;', type: 'property', detail: 'Top' },
    { label: 'transform', value: 'transform: translate(0,0);', type: 'property', detail: 'Transform' },
    { label: 'transform-origin', value: 'transform-origin: center;', type: 'property', detail: 'Transform Origin' },
    { label: 'transition', value: 'transition: all 0.3s ease;', type: 'property', detail: 'Transition' },
    { label: 'transition-delay', value: 'transition-delay: 0s;', type: 'property', detail: 'Trans Delay' },
    { label: 'transition-duration', value: 'transition-duration: 0.3s;', type: 'property', detail: 'Trans Duration' },
    { label: 'transition-property', value: 'transition-property: all;', type: 'property', detail: 'Trans Property' },
    { label: 'transition-timing-function', value: 'transition-timing-function: ease-in-out;', type: 'property', detail: 'Trans Timing' },
    { label: 'user-select', value: 'user-select: none;', type: 'property', detail: 'User Select' },
    { label: 'vertical-align', value: 'vertical-align: middle;', type: 'property', detail: 'Vertical Align' },
    { label: 'visibility', value: 'visibility: hidden;', type: 'property', detail: 'Visibility' },
    { label: 'white-space', value: 'white-space: nowrap;', type: 'property', detail: 'White Space' },
    { label: 'width', value: 'width: 100%;', type: 'property', detail: 'Width' },
    { label: 'will-change', value: 'will-change: transform;', type: 'property', detail: 'Will Change' },
    { label: 'word-break', value: 'word-break: break-all;', type: 'property', detail: 'Word Break' },
    { label: 'word-spacing', value: 'word-spacing: 1px;', type: 'property', detail: 'Word Spacing' },
    { label: 'word-wrap', value: 'word-wrap: break-word;', type: 'property', detail: 'Word Wrap' },
    { label: 'writing-mode', value: 'writing-mode: vertical-rl;', type: 'property', detail: 'Writing Mode' },
    { label: 'z-index', value: 'z-index: 10;', type: 'property', detail: 'Z Index' },
];

export const JS_KEYWORDS: Suggestion[] = [
  { label: 'addEventListener', value: 'addEventListener("$0", (e) => {\n\t\n});', type: 'snippet', detail: 'Add Listener' },
  { label: 'alert', value: 'alert("$0");', type: 'snippet', detail: 'Alert' },
  { label: 'Array.from', value: 'Array.from($0)', type: 'snippet', detail: 'Array From' },
  { label: 'Array.isArray', value: 'Array.isArray($0)', type: 'snippet', detail: 'Is Array' },
  { label: 'async', value: 'async function $0() {}', type: 'keyword', detail: 'Async' },
  { label: 'await', value: 'await $0', type: 'keyword', detail: 'Await' },
  { label: 'break', value: 'break;', type: 'keyword', detail: 'Break' },
  { label: 'case', value: 'case $0:', type: 'keyword', detail: 'Case' },
  { label: 'catch', value: 'catch (error) {\n\t$0\n}', type: 'keyword', detail: 'Catch' },
  { label: 'class', value: 'class $0 {\n\tconstructor() {\n\t\t\n\t}\n}', type: 'keyword', detail: 'Class' },
  { label: 'console.error', value: 'console.error($0);', type: 'snippet', detail: 'Log Error' },
  { label: 'console.log', value: 'console.log($0);', type: 'snippet', detail: 'Log' },
  { label: 'console.table', value: 'console.table($0);', type: 'snippet', detail: 'Log Table' },
  { label: 'console.warn', value: 'console.warn($0);', type: 'snippet', detail: 'Log Warn' },
  { label: 'const', value: 'const $0 = ', type: 'keyword', detail: 'Const' },
  { label: 'continue', value: 'continue;', type: 'keyword', detail: 'Continue' },
  { label: 'Date.now', value: 'Date.now()', type: 'snippet', detail: 'Date Now' },
  { label: 'debugger', value: 'debugger;', type: 'keyword', detail: 'Debugger' },
  { label: 'default', value: 'default:', type: 'keyword', detail: 'Default' },
  { label: 'delete', value: 'delete $0', type: 'keyword', detail: 'Delete' },
  { label: 'do', value: 'do {\n\t$0\n} while (condition);', type: 'keyword', detail: 'Do While' },
  { label: 'document.createElement', value: 'document.createElement("$0")', type: 'snippet', detail: 'Create Element' },
  { label: 'document.getElementById', value: 'document.getElementById("$0")', type: 'snippet', detail: 'Get By ID' },
  { label: 'document.querySelector', value: 'document.querySelector("$0")', type: 'snippet', detail: 'Query Selector' },
  { label: 'document.querySelectorAll', value: 'document.querySelectorAll("$0")', type: 'snippet', detail: 'Query All' },
  { label: 'else', value: 'else {\n\t$0\n}', type: 'keyword', detail: 'Else' },
  { label: 'export', value: 'export default $0;', type: 'keyword', detail: 'Export' },
  { label: 'extends', value: 'extends $0', type: 'keyword', detail: 'Extends' },
  { label: 'fetch', value: 'fetch("$0")\n\t.then(res => res.json())\n\t.then(data => console.log(data));', type: 'snippet', detail: 'Fetch' },
  { label: 'fetch:post', value: 'fetch("$0", {\n\tmethod: "POST",\n\theaders: {\n\t\t"Content-Type": "application/json"\n\t},\n\tbody: JSON.stringify(data)\n});', type: 'snippet', detail: 'Fetch POST' },
  { label: 'filter', value: 'filter((item) => $0)', type: 'snippet', detail: 'Array Filter' },
  { label: 'finally', value: 'finally {\n\t$0\n}', type: 'keyword', detail: 'Finally' },
  { label: 'find', value: 'find((item) => $0)', type: 'snippet', detail: 'Array Find' },
  { label: 'for', value: 'for (let i = 0; i < $0; i++) {\n\t\n}', type: 'keyword', detail: 'For Loop' },
  { label: 'forEach', value: 'forEach((item) => {\n\t$0\n})', type: 'snippet', detail: 'Array ForEach' },
  { label: 'function', value: 'function $0() {\n\t\n}', type: 'keyword', detail: 'Function' },
  { label: 'if', value: 'if ($0) {\n\t\n}', type: 'keyword', detail: 'If' },
  { label: 'import', value: 'import $0 from "";', type: 'keyword', detail: 'Import' },
  { label: 'in', value: 'in', type: 'keyword', detail: 'In' },
  { label: 'includes', value: 'includes($0)', type: 'snippet', detail: 'Array Includes' },
  { label: 'instanceof', value: 'instanceof', type: 'keyword', detail: 'Instanceof' },
  { label: 'join', value: 'join("$0")', type: 'snippet', detail: 'Array Join' },
  { label: 'JSON.parse', value: 'JSON.parse($0)', type: 'snippet', detail: 'Parse JSON' },
  { label: 'JSON.stringify', value: 'JSON.stringify($0)', type: 'snippet', detail: 'Stringify JSON' },
  { label: 'let', value: 'let $0 = ', type: 'keyword', detail: 'Let' },
  { label: 'localStorage.getItem', value: 'localStorage.getItem("$0")', type: 'snippet', detail: 'Local Get' },
  { label: 'localStorage.setItem', value: 'localStorage.setItem("$0", value)', type: 'snippet', detail: 'Local Set' },
  { label: 'map', value: 'map((item) => $0)', type: 'snippet', detail: 'Array Map' },
  { label: 'Math.ceil', value: 'Math.ceil($0)', type: 'snippet', detail: 'Math Ceil' },
  { label: 'Math.floor', value: 'Math.floor($0)', type: 'snippet', detail: 'Math Floor' },
  { label: 'Math.max', value: 'Math.max($0)', type: 'snippet', detail: 'Math Max' },
  { label: 'Math.min', value: 'Math.min($0)', type: 'snippet', detail: 'Math Min' },
  { label: 'Math.random', value: 'Math.random()', type: 'snippet', detail: 'Math Random' },
  { label: 'Math.round', value: 'Math.round($0)', type: 'snippet', detail: 'Math Round' },
  { label: 'new', value: 'new $0()', type: 'keyword', detail: 'New' },
  { label: 'new Promise', value: 'new Promise((resolve, reject) => {\n\t$0\n})', type: 'snippet', detail: 'New Promise' },
  { label: 'Object.entries', value: 'Object.entries($0)', type: 'snippet', detail: 'Object Entries' },
  { label: 'Object.keys', value: 'Object.keys($0)', type: 'snippet', detail: 'Object Keys' },
  { label: 'Object.values', value: 'Object.values($0)', type: 'snippet', detail: 'Object Values' },
  { label: 'pop', value: 'pop()', type: 'snippet', detail: 'Array Pop' },
  { label: 'Promise.all', value: 'Promise.all([$0])', type: 'snippet', detail: 'Promise All' },
  { label: 'push', value: 'push($0)', type: 'snippet', detail: 'Array Push' },
  { label: 'reduce', value: 'reduce((acc, curr) => {\n\treturn acc;\n}, initial)', type: 'snippet', detail: 'Array Reduce' },
  { label: 'removeEventListener', value: 'removeEventListener("$0", handler);', type: 'snippet', detail: 'Remove Listener' },
  { label: 'return', value: 'return $0;', type: 'keyword', detail: 'Return' },
  { label: 'shift', value: 'shift()', type: 'snippet', detail: 'Array Shift' },
  { label: 'setInterval', value: 'setInterval(() => {\n\t$0\n}, 1000);', type: 'snippet', detail: 'Set Interval' },
  { label: 'setTimeout', value: 'setTimeout(() => {\n\t$0\n}, 1000);', type: 'snippet', detail: 'Set Timeout' },
  { label: 'slice', value: 'slice($0)', type: 'snippet', detail: 'Array Slice' },
  { label: 'sort', value: 'sort((a, b) => a - b)', type: 'snippet', detail: 'Array Sort' },
  { label: 'splice', value: 'splice($0, 1)', type: 'snippet', detail: 'Array Splice' },
  { label: 'split', value: 'split("$0")', type: 'snippet', detail: 'String Split' },
  { label: 'super', value: 'super($0);', type: 'keyword', detail: 'Super' },
  { label: 'switch', value: 'switch ($0) {\n\tcase value:\n\t\tbreak;\n\tdefault:\n\t\tbreak;\n}', type: 'keyword', detail: 'Switch' },
  { label: 'this', value: 'this', type: 'keyword', detail: 'This' },
  { label: 'throw', value: 'throw new Error("$0");', type: 'keyword', detail: 'Throw' },
  { label: 'try', value: 'try {\n\t$0\n} catch (e) {\n\tconsole.error(e);\n}', type: 'keyword', detail: 'Try Catch' },
  { label: 'typeof', value: 'typeof $0', type: 'keyword', detail: 'Typeof' },
  { label: 'unshift', value: 'unshift($0)', type: 'snippet', detail: 'Array Unshift' },
  { label: 'var', value: 'var $0', type: 'keyword', detail: 'Var' },
  { label: 'void', value: 'void', type: 'keyword', detail: 'Void' },
  { label: 'while', value: 'while ($0) {\n\t\n}', type: 'keyword', detail: 'While' },
  { label: 'window', value: 'window', type: 'keyword', detail: 'Window' },
  { label: 'yield', value: 'yield $0', type: 'keyword', detail: 'Yield' },
];
