import { Suggestion } from './types';

// $0 represents where the cursor will be placed after insertion

export const HTML_TAGS: Suggestion[] = [
  // --- Document Structure ---
  { label: 'html', value: '<html lang="en">\n$0\n</html>', type: 'tag' },
  { label: 'head', value: '<head>\n\t$0\n</head>', type: 'tag' },
  { label: 'body', value: '<body>\n\t$0\n</body>', type: 'tag' },
  { label: 'meta', value: '<meta name="viewport" content="width=device-width, initial-scale=1.0" />', type: 'tag' },
  { label: 'title', value: '<title>$0</title>', type: 'tag' },
  { label: 'link', value: '<link rel="stylesheet" href="$0" />', type: 'tag' },
  { label: 'script', value: '<script src="$0"></script>', type: 'tag' },
  { label: 'style', value: '<style>\n\t$0\n</style>', type: 'tag' },

  // --- Content Sectioning ---
  { label: 'address', value: '<address>$0</address>', type: 'tag' },
  { label: 'article', value: '<article>$0</article>', type: 'tag' },
  { label: 'aside', value: '<aside>$0</aside>', type: 'tag' },
  { label: 'footer', value: '<footer>$0</footer>', type: 'tag' },
  { label: 'header', value: '<header>$0</header>', type: 'tag' },
  { label: 'h1', value: '<h1>$0</h1>', type: 'tag' },
  { label: 'h2', value: '<h2>$0</h2>', type: 'tag' },
  { label: 'h3', value: '<h3>$0</h3>', type: 'tag' },
  { label: 'h4', value: '<h4>$0</h4>', type: 'tag' },
  { label: 'h5', value: '<h5>$0</h5>', type: 'tag' },
  { label: 'h6', value: '<h6>$0</h6>', type: 'tag' },
  { label: 'main', value: '<main>$0</main>', type: 'tag' },
  { label: 'nav', value: '<nav>$0</nav>', type: 'tag' },
  { label: 'section', value: '<section>$0</section>', type: 'tag' },

  // --- Text Content ---
  { label: 'blockquote', value: '<blockquote>$0</blockquote>', type: 'tag' },
  { label: 'dd', value: '<dd>$0</dd>', type: 'tag' },
  { label: 'div', value: '<div>$0</div>', type: 'tag' },
  { label: 'dl', value: '<dl>\n\t<dt></dt>\n\t<dd></dd>\n</dl>', type: 'tag' },
  { label: 'dt', value: '<dt>$0</dt>', type: 'tag' },
  { label: 'figcaption', value: '<figcaption>$0</figcaption>', type: 'tag' },
  { label: 'figure', value: '<figure>\n\t<img src="" alt="" />\n\t<figcaption>$0</figcaption>\n</figure>', type: 'tag' },
  { label: 'hr', value: '<hr />', type: 'tag' },
  { label: 'li', value: '<li>$0</li>', type: 'tag' },
  { label: 'ol', value: '<ol>\n\t<li>$0</li>\n</ol>', type: 'tag' },
  { label: 'p', value: '<p>$0</p>', type: 'tag' },
  { label: 'pre', value: '<pre>$0</pre>', type: 'tag' },
  { label: 'ul', value: '<ul>\n\t<li>$0</li>\n</ul>', type: 'tag' },

  // --- Inline Text Semantics ---
  { label: 'a', value: '<a href="$0"></a>', type: 'tag' },
  { label: 'abbr', value: '<abbr title="$0"></abbr>', type: 'tag' },
  { label: 'b', value: '<b>$0</b>', type: 'tag' },
  { label: 'bdi', value: '<bdi>$0</bdi>', type: 'tag' },
  { label: 'bdo', value: '<bdo dir="">$0</bdo>', type: 'tag' },
  { label: 'br', value: '<br />', type: 'tag' },
  { label: 'cite', value: '<cite>$0</cite>', type: 'tag' },
  { label: 'code', value: '<code>$0</code>', type: 'tag' },
  { label: 'data', value: '<data value="">$0</data>', type: 'tag' },
  { label: 'dfn', value: '<dfn>$0</dfn>', type: 'tag' },
  { label: 'em', value: '<em>$0</em>', type: 'tag' },
  { label: 'i', value: '<i>$0</i>', type: 'tag' },
  { label: 'kbd', value: '<kbd>$0</kbd>', type: 'tag' },
  { label: 'mark', value: '<mark>$0</mark>', type: 'tag' },
  { label: 'q', value: '<q>$0</q>', type: 'tag' },
  { label: 's', value: '<s>$0</s>', type: 'tag' },
  { label: 'samp', value: '<samp>$0</samp>', type: 'tag' },
  { label: 'small', value: '<small>$0</small>', type: 'tag' },
  { label: 'span', value: '<span>$0</span>', type: 'tag' },
  { label: 'strong', value: '<strong>$0</strong>', type: 'tag' },
  { label: 'sub', value: '<sub>$0</sub>', type: 'tag' },
  { label: 'sup', value: '<sup>$0</sup>', type: 'tag' },
  { label: 'time', value: '<time datetime="">$0</time>', type: 'tag' },
  { label: 'u', value: '<u>$0</u>', type: 'tag' },
  { label: 'var', value: '<var>$0</var>', type: 'tag' },

  // --- Image & Multimedia ---
  { label: 'audio', value: '<audio src="$0" controls></audio>', type: 'tag' },
  { label: 'img', value: '<img src="$0" alt="" />', type: 'tag' },
  { label: 'map', value: '<map name="">$0</map>', type: 'tag' },
  { label: 'area', value: '<area shape="" coords="" href="" alt="" />', type: 'tag' },
  { label: 'track', value: '<track src="" kind="" srclang="" label="" />', type: 'tag' },
  { label: 'video', value: '<video src="$0" controls></video>', type: 'tag' },

  // --- Embedded Content ---
  { label: 'embed', value: '<embed src="$0" type="" />', type: 'tag' },
  { label: 'iframe', value: '<iframe src="$0" frameborder="0"></iframe>', type: 'tag' },
  { label: 'object', value: '<object data="" type="">$0</object>', type: 'tag' },
  { label: 'param', value: '<param name="" value="" />', type: 'tag' },
  { label: 'picture', value: '<picture>\n\t<source srcset="" type="" />\n\t<img src="" alt="" />\n</picture>', type: 'tag' },
  { label: 'source', value: '<source src="$0" type="video/mp4" />', type: 'tag' },
  { label: 'portal', value: '<portal src="$0"></portal>', type: 'tag' },

  // --- SVG Tags (Graphics & Filters) ---
  { label: 'svg', value: '<svg width="100" height="100" viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">\n\t$0\n</svg>', type: 'tag' },
  { label: 'path', value: '<path d="$0" fill="none" stroke="black" />', type: 'tag' },
  { label: 'rect', value: '<rect x="0" y="0" width="100" height="100" fill="black" />', type: 'tag' },
  { label: 'circle', value: '<circle cx="50" cy="50" r="40" fill="black" />', type: 'tag' },
  { label: 'ellipse', value: '<ellipse cx="50" cy="50" rx="40" ry="20" fill="black" />', type: 'tag' },
  { label: 'line', value: '<line x1="0" y1="0" x2="100" y2="100" stroke="black" />', type: 'tag' },
  { label: 'polyline', value: '<polyline points="0,0 100,100" stroke="black" fill="none" />', type: 'tag' },
  { label: 'polygon', value: '<polygon points="0,0 100,100" stroke="black" fill="none" />', type: 'tag' },
  { label: 'g', value: '<g>\n\t$0\n</g>', type: 'tag' },
  { label: 'defs', value: '<defs>\n\t$0\n</defs>', type: 'tag' },
  { label: 'use', value: '<use href="#$0" x="0" y="0" />', type: 'tag' },
  { label: 'symbol', value: '<symbol id="$0" viewBox="0 0 100 100">\n\t\n</symbol>', type: 'tag' },
  { label: 'marker', value: '<marker id="$0" markerWidth="10" markerHeight="10" refX="5" refY="5" orient="auto">\n\t\n</marker>', type: 'tag' },
  { label: 'pattern', value: '<pattern id="$0" x="0" y="0" width="1" height="1" patternUnits="objectBoundingBox">\n\t\n</pattern>', type: 'tag' },
  { label: 'mask', value: '<mask id="$0">\n\t\n</mask>', type: 'tag' },
  { label: 'clipPath', value: '<clipPath id="$0">\n\t\n</clipPath>', type: 'tag' },
  { label: 'text', value: '<text x="0" y="0">$0</text>', type: 'tag' },
  { label: 'tspan', value: '<tspan>$0</tspan>', type: 'tag' },
  { label: 'linearGradient', value: '<linearGradient id="$0" x1="0%" y1="0%" x2="100%" y2="0%">\n\t<stop offset="0%" stop-color="black" />\n\t<stop offset="100%" stop-color="white" />\n</linearGradient>', type: 'tag' },
  { label: 'radialGradient', value: '<radialGradient id="$0">\n\t<stop offset="0%" stop-color="black" />\n\t<stop offset="100%" stop-color="white" />\n</radialGradient>', type: 'tag' },
  { label: 'stop', value: '<stop offset="$0" stop-color="black" />', type: 'tag' },
  { label: 'filter', value: '<filter id="$0">\n\t\n</filter>', type: 'tag' },
  
  // --- SVG Filters (FE) ---
  { label: 'feGaussianBlur', value: '<feGaussianBlur in="SourceGraphic" stdDeviation="5" />', type: 'tag' },
  { label: 'feOffset', value: '<feOffset dx="0" dy="0" />', type: 'tag' },
  { label: 'feBlend', value: '<feBlend mode="normal" in="SourceGraphic" in2="SourceAlpha" />', type: 'tag' },
  { label: 'feColorMatrix', value: '<feColorMatrix type="matrix" values="" />', type: 'tag' },
  { label: 'feComponentTransfer', value: '<feComponentTransfer>\n\t$0\n</feComponentTransfer>', type: 'tag' },
  { label: 'feComposite', value: '<feComposite operator="over" in="SourceGraphic" in2="SourceAlpha" />', type: 'tag' },
  { label: 'feConvolveMatrix', value: '<feConvolveMatrix order="3" kernelMatrix="" />', type: 'tag' },
  { label: 'feDiffuseLighting', value: '<feDiffuseLighting lighting-color="white">\n\t$0\n</feDiffuseLighting>', type: 'tag' },
  { label: 'feDisplacementMap', value: '<feDisplacementMap in="SourceGraphic" in2="SourceAlpha" scale="0" xChannelSelector="R" yChannelSelector="G" />', type: 'tag' },
  { label: 'feDistantLight', value: '<feDistantLight azimuth="0" elevation="0" />', type: 'tag' },
  { label: 'feDropShadow', value: '<feDropShadow dx="0" dy="0" stdDeviation="0" />', type: 'tag' },
  { label: 'feFlood', value: '<feFlood flood-color="black" flood-opacity="1" />', type: 'tag' },
  { label: 'feFuncA', value: '<feFuncA type="identity" />', type: 'tag' },
  { label: 'feFuncB', value: '<feFuncB type="identity" />', type: 'tag' },
  { label: 'feFuncG', value: '<feFuncG type="identity" />', type: 'tag' },
  { label: 'feFuncR', value: '<feFuncR type="identity" />', type: 'tag' },
  { label: 'feImage', value: '<feImage href="$0" />', type: 'tag' },
  { label: 'feMerge', value: '<feMerge>\n\t<feMergeNode in="" />\n</feMerge>\n', type: 'tag' },
  { label: 'feMergeNode', value: '<feMergeNode in="$0" />', type: 'tag' },
  { label: 'feMorphology', value: '<feMorphology operator="erode" radius="0" />', type: 'tag' },
  { label: 'fePointLight', value: '<fePointLight x="0" y="0" z="0" />', type: 'tag' },
  { label: 'feSpecularLighting', value: '<feSpecularLighting lighting-color="white">\n\t$0\n</feSpecularLighting>', type: 'tag' },
  { label: 'feSpotLight', value: '<feSpotLight x="0" y="0" z="0" pointsAtX="0" pointsAtY="0" pointsAtZ="0" />', type: 'tag' },
  { label: 'feTile', value: '<feTile in="" />', type: 'tag' },
  { label: 'feTurbulence', value: '<feTurbulence type="turbulence" baseFrequency="0.05" numOctaves="1" result="turbulence" />', type: 'tag' },

  // --- Forms ---
  { label: 'button', value: '<button>$0</button>', type: 'tag' },
  { label: 'datalist', value: '<datalist id="">\n\t<option value="">\n</datalist>', type: 'tag' },
  { label: 'fieldset', value: '<fieldset>\n\t<legend>$0</legend>\n</fieldset>', type: 'tag' },
  { label: 'form', value: '<form action="$0" method="POST"></form>', type: 'tag' },
  { label: 'input', value: '<input type="text" placeholder="$0" />', type: 'tag' },
  { label: 'label', value: '<label for="$0"></label>', type: 'tag' },
  { label: 'legend', value: '<legend>$0</legend>', type: 'tag' },
  { label: 'meter', value: '<meter value="" min="" max="">$0</meter>', type: 'tag' },
  { label: 'optgroup', value: '<optgroup label="">$0</optgroup>', type: 'tag' },
  { label: 'option', value: '<option value="$0"></option>', type: 'tag' },
  { label: 'output', value: '<output name="">$0</output>', type: 'tag' },
  { label: 'progress', value: '<progress value="" max="">$0</progress>', type: 'tag' },
  { label: 'select', value: '<select name="$0" id=""></select>', type: 'tag' },
  { label: 'textarea', value: '<textarea name="$0" id="" cols="30" rows="10"></textarea>', type: 'tag' },

  // --- Interactive ---
  { label: 'details', value: '<details>\n\t<summary>Title</summary>\n\t$0\n</details>', type: 'tag' },
  { label: 'dialog', value: '<dialog open>$0</dialog>', type: 'tag' },
  { label: 'menu', value: '<menu>\n\t<li>$0</li>\n</menu>', type: 'tag' },
  { label: 'summary', value: '<summary>$0</summary>', type: 'tag' },

  // --- Tables ---
  { label: 'caption', value: '<caption>$0</caption>', type: 'tag' },
  { label: 'col', value: '<col span="" class="" />', type: 'tag' },
  { label: 'colgroup', value: '<colgroup>\n\t<col />\n</colgroup>', type: 'tag' },
  { label: 'table', value: '<table>\n\t<thead>\n\t\t<tr>\n\t\t\t<th>$0</th>\n\t\t</tr>\n\t</thead>\n\t<tbody>\n\t\t<tr>\n\t\t\t<td></td>\n\t\t</tr>\n\t</tbody>\n</table>', type: 'tag' },
  { label: 'tbody', value: '<tbody>$0</tbody>', type: 'tag' },
  { label: 'td', value: '<td>$0</td>', type: 'tag' },
  { label: 'tfoot', value: '<tfoot>$0</tfoot>', type: 'tag' },
  { label: 'th', value: '<th>$0</th>', type: 'tag' },
  { label: 'thead', value: '<thead>$0</thead>', type: 'tag' },
  { label: 'tr', value: '<tr>$0</tr>', type: 'tag' },
  
  // --- Attributes ---
  { label: 'class', value: 'class="$0"', type: 'property' },
  { label: 'id', value: 'id="$0"', type: 'property' },
  { label: 'style', value: 'style="$0"', type: 'property' },
  { label: 'src', value: 'src="$0"', type: 'property' },
  { label: 'href', value: 'href="$0"', type: 'property' },
  { label: 'alt', value: 'alt="$0"', type: 'property' },
  { label: 'title', value: 'title="$0"', type: 'property' },
  { label: 'type', value: 'type="$0"', type: 'property' },
  { label: 'width', value: 'width="$0"', type: 'property' },
  { label: 'height', value: 'height="$0"', type: 'property' },
  { label: 'placeholder', value: 'placeholder="$0"', type: 'property' },
  { label: 'required', value: 'required', type: 'property' },
  { label: 'disabled', value: 'disabled', type: 'property' },
  { label: 'checked', value: 'checked', type: 'property' },
  { label: 'selected', value: 'selected', type: 'property' },
  { label: 'readonly', value: 'readonly', type: 'property' },
  { label: 'multiple', value: 'multiple', type: 'property' },
];

export const CSS_PROPS: Suggestion[] = [
  // A
  { label: 'accent-color', value: 'accent-color: auto;', type: 'property' },
  { label: 'align-content', value: 'align-content: center;', type: 'property' },
  { label: 'align-items', value: 'align-items: center;', type: 'property' },
  { label: 'align-self', value: 'align-self: center;', type: 'property' },
  { label: 'all', value: 'all: unset;', type: 'property' },
  { label: 'alignment-baseline', value: 'alignment-baseline: middle;', type: 'property' },
  { label: 'animation', value: 'animation: name duration timing-function delay iteration-count direction fill-mode;', type: 'property' },
  { label: 'animation-delay', value: 'animation-delay: 0s;', type: 'property' },
  { label: 'animation-direction', value: 'animation-direction: normal;', type: 'property' },
  { label: 'animation-duration', value: 'animation-duration: 0s;', type: 'property' },
  { label: 'animation-fill-mode', value: 'animation-fill-mode: forwards;', type: 'property' },
  { label: 'animation-iteration-count', value: 'animation-iteration-count: infinite;', type: 'property' },
  { label: 'animation-name', value: 'animation-name: none;', type: 'property' },
  { label: 'animation-play-state', value: 'animation-play-state: running;', type: 'property' },
  { label: 'animation-timing-function', value: 'animation-timing-function: ease;', type: 'property' },
  { label: 'aspect-ratio', value: 'aspect-ratio: 16 / 9;', type: 'property' },
  
  // B
  { label: 'backdrop-filter', value: 'backdrop-filter: blur(10px);', type: 'property' },
  { label: 'backface-visibility', value: 'backface-visibility: hidden;', type: 'property' },
  { label: 'background', value: 'background: $0;', type: 'property' },
  { label: 'background-attachment', value: 'background-attachment: fixed;', type: 'property' },
  { label: 'background-blend-mode', value: 'background-blend-mode: normal;', type: 'property' },
  { label: 'background-clip', value: 'background-clip: border-box;', type: 'property' },
  { label: 'background-color', value: 'background-color: $0;', type: 'property' },
  { label: 'background-image', value: 'background-image: url($0);', type: 'property' },
  { label: 'background-origin', value: 'background-origin: padding-box;', type: 'property' },
  { label: 'background-position', value: 'background-position: center;', type: 'property' },
  { label: 'background-repeat', value: 'background-repeat: no-repeat;', type: 'property' },
  { label: 'background-size', value: 'background-size: cover;', type: 'property' },
  { label: 'baseline-shift', value: 'baseline-shift: sub;', type: 'property' },
  { label: 'block-size', value: 'block-size: auto;', type: 'property' },
  { label: 'border', value: 'border: 1px solid $0;', type: 'property' },
  { label: 'border-bottom', value: 'border-bottom: 1px solid $0;', type: 'property' },
  { label: 'border-collapse', value: 'border-collapse: collapse;', type: 'property' },
  { label: 'border-color', value: 'border-color: $0;', type: 'property' },
  { label: 'border-radius', value: 'border-radius: 4px;', type: 'property' },
  { label: 'border-spacing', value: 'border-spacing: 0;', type: 'property' },
  { label: 'border-style', value: 'border-style: solid;', type: 'property' },
  { label: 'border-top', value: 'border-top: 1px solid $0;', type: 'property' },
  { label: 'border-width', value: 'border-width: 1px;', type: 'property' },
  { label: 'bottom', value: 'bottom: 0;', type: 'property' },
  { label: 'box-decoration-break', value: 'box-decoration-break: clone;', type: 'property' },
  { label: 'box-shadow', value: 'box-shadow: 0 4px 6px rgba(0,0,0,0.1);', type: 'property' },
  { label: 'box-sizing', value: 'box-sizing: border-box;', type: 'property' },
  { label: 'break-after', value: 'break-after: auto;', type: 'property' },
  { label: 'break-before', value: 'break-before: auto;', type: 'property' },
  { label: 'break-inside', value: 'break-inside: avoid;', type: 'property' },

  // C
  { label: 'caption-side', value: 'caption-side: bottom;', type: 'property' },
  { label: 'caret-color', value: 'caret-color: auto;', type: 'property' },
  { label: 'clear', value: 'clear: both;', type: 'property' },
  { label: 'clip', value: 'clip: auto;', type: 'property' },
  { label: 'clip-path', value: 'clip-path: circle(50%);', type: 'property' },
  { label: 'color', value: 'color: $0;', type: 'property' },
  { label: 'color-scheme', value: 'color-scheme: light dark;', type: 'property' },
  { label: 'column-count', value: 'column-count: 3;', type: 'property' },
  { label: 'column-fill', value: 'column-fill: balance;', type: 'property' },
  { label: 'column-gap', value: 'column-gap: normal;', type: 'property' },
  { label: 'column-rule', value: 'column-rule: 1px solid black;', type: 'property' },
  { label: 'column-span', value: 'column-span: all;', type: 'property' },
  { label: 'column-width', value: 'column-width: auto;', type: 'property' },
  { label: 'content', value: "content: '';", type: 'property' },
  { label: 'counter-increment', value: 'counter-increment: none;', type: 'property' },
  { label: 'counter-reset', value: 'counter-reset: none;', type: 'property' },
  { label: 'cursor', value: 'cursor: pointer;', type: 'property' },

  // D
  { label: 'direction', value: 'direction: ltr;', type: 'property' },
  { label: 'display', value: 'display: flex;', type: 'property' },
  { label: 'dominant-baseline', value: 'dominant-baseline: middle;', type: 'property' },
  
  // E
  { label: 'empty-cells', value: 'empty-cells: show;', type: 'property' },

  // F
  { label: 'fill', value: 'fill: $0;', type: 'property' },
  { label: 'fill-opacity', value: 'fill-opacity: 1;', type: 'property' },
  { label: 'fill-rule', value: 'fill-rule: nonzero;', type: 'property' },
  { label: 'filter', value: 'filter: none;', type: 'property' },
  { label: 'flex', value: 'flex: 1;', type: 'property' },
  { label: 'flex-basis', value: 'flex-basis: auto;', type: 'property' },
  { label: 'flex-direction', value: 'flex-direction: column;', type: 'property' },
  { label: 'flex-flow', value: 'flex-flow: row wrap;', type: 'property' },
  { label: 'flex-grow', value: 'flex-grow: 0;', type: 'property' },
  { label: 'flex-shrink', value: 'flex-shrink: 1;', type: 'property' },
  { label: 'flex-wrap', value: 'flex-wrap: wrap;', type: 'property' },
  { label: 'float', value: 'float: left;', type: 'property' },
  { label: 'flood-color', value: 'flood-color: black;', type: 'property' },
  { label: 'flood-opacity', value: 'flood-opacity: 1;', type: 'property' },
  { label: 'font', value: 'font: normal 16px sans-serif;', type: 'property' },
  { label: 'font-family', value: 'font-family: sans-serif;', type: 'property' },
  { label: 'font-feature-settings', value: 'font-feature-settings: normal;', type: 'property' },
  { label: 'font-kerning', value: 'font-kerning: auto;', type: 'property' },
  { label: 'font-size', value: 'font-size: 16px;', type: 'property' },
  { label: 'font-size-adjust', value: 'font-size-adjust: none;', type: 'property' },
  { label: 'font-stretch', value: 'font-stretch: normal;', type: 'property' },
  { label: 'font-style', value: 'font-style: italic;', type: 'property' },
  { label: 'font-variant', value: 'font-variant: normal;', type: 'property' },
  { label: 'font-weight', value: 'font-weight: bold;', type: 'property' },

  // G
  { label: 'gap', value: 'gap: 1rem;', type: 'property' },
  { label: 'grid', value: 'grid: none;', type: 'property' },
  { label: 'grid-area', value: 'grid-area: auto;', type: 'property' },
  { label: 'grid-auto-columns', value: 'grid-auto-columns: auto;', type: 'property' },
  { label: 'grid-auto-flow', value: 'grid-auto-flow: row;', type: 'property' },
  { label: 'grid-auto-rows', value: 'grid-auto-rows: auto;', type: 'property' },
  { label: 'grid-column', value: 'grid-column: auto;', type: 'property' },
  { label: 'grid-column-end', value: 'grid-column-end: auto;', type: 'property' },
  { label: 'grid-column-gap', value: 'grid-column-gap: 0;', type: 'property' },
  { label: 'grid-column-start', value: 'grid-column-start: auto;', type: 'property' },
  { label: 'grid-gap', value: 'grid-gap: 0;', type: 'property' },
  { label: 'grid-row', value: 'grid-row: auto;', type: 'property' },
  { label: 'grid-row-end', value: 'grid-row-end: auto;', type: 'property' },
  { label: 'grid-row-gap', value: 'grid-row-gap: 0;', type: 'property' },
  { label: 'grid-row-start', value: 'grid-row-start: auto;', type: 'property' },
  { label: 'grid-template', value: 'grid-template: none;', type: 'property' },
  { label: 'grid-template-areas', value: 'grid-template-areas: none;', type: 'property' },
  { label: 'grid-template-columns', value: 'grid-template-columns: repeat(3, 1fr);', type: 'property' },
  { label: 'grid-template-rows', value: 'grid-template-rows: none;', type: 'property' },

  // H
  { label: 'height', value: 'height: $0;', type: 'property' },
  { label: 'hyphens', value: 'hyphens: manual;', type: 'property' },
  { label: 'hyphenate-character', value: 'hyphenate-character: auto;', type: 'property' },

  // I
  { label: 'image-rendering', value: 'image-rendering: auto;', type: 'property' },
  { label: 'inline-size', value: 'inline-size: auto;', type: 'property' },
  { label: 'inset', value: 'inset: 0;', type: 'property' },
  { label: 'isolation', value: 'isolation: isolate;', type: 'property' },

  // J
  { label: 'justify-content', value: 'justify-content: center;', type: 'property' },
  { label: 'justify-items', value: 'justify-items: center;', type: 'property' },
  { label: 'justify-self', value: 'justify-self: center;', type: 'property' },

  // L
  { label: 'left', value: 'left: 0;', type: 'property' },
  { label: 'letter-spacing', value: 'letter-spacing: normal;', type: 'property' },
  { label: 'lighting-color', value: 'lighting-color: white;', type: 'property' },
  { label: 'line-break', value: 'line-break: auto;', type: 'property' },
  { label: 'line-height', value: 'line-height: 1.5;', type: 'property' },
  { label: 'list-style', value: 'list-style: none;', type: 'property' },
  { label: 'list-style-image', value: 'list-style-image: none;', type: 'property' },
  { label: 'list-style-position', value: 'list-style-position: outside;', type: 'property' },
  { label: 'list-style-type', value: 'list-style-type: none;', type: 'property' },

  // M
  { label: 'margin', value: 'margin: 0;', type: 'property' },
  { label: 'margin-bottom', value: 'margin-bottom: 0;', type: 'property' },
  { label: 'margin-left', value: 'margin-left: 0;', type: 'property' },
  { label: 'margin-right', value: 'margin-right: 0;', type: 'property' },
  { label: 'margin-top', value: 'margin-top: 0;', type: 'property' },
  { label: 'marker', value: 'marker: none;', type: 'property' },
  { label: 'marker-end', value: 'marker-end: none;', type: 'property' },
  { label: 'marker-mid', value: 'marker-mid: none;', type: 'property' },
  { label: 'marker-start', value: 'marker-start: none;', type: 'property' },
  { label: 'mask', value: 'mask: none;', type: 'property' },
  { label: 'mask-type', value: 'mask-type: luminance;', type: 'property' },
  { label: 'max-block-size', value: 'max-block-size: none;', type: 'property' },
  { label: 'max-height', value: 'max-height: none;', type: 'property' },
  { label: 'max-inline-size', value: 'max-inline-size: none;', type: 'property' },
  { label: 'max-width', value: 'max-width: none;', type: 'property' },
  { label: 'min-block-size', value: 'min-block-size: 0;', type: 'property' },
  { label: 'min-height', value: 'min-height: 0;', type: 'property' },
  { label: 'min-inline-size', value: 'min-inline-size: 0;', type: 'property' },
  { label: 'min-width', value: 'min-width: 0;', type: 'property' },
  { label: 'mix-blend-mode', value: 'mix-blend-mode: normal;', type: 'property' },

  // O
  { label: 'object-fit', value: 'object-fit: cover;', type: 'property' },
  { label: 'object-position', value: 'object-position: 50% 50%;', type: 'property' },
  { label: 'offset', value: 'offset: none;', type: 'property' },
  { label: 'opacity', value: 'opacity: 1;', type: 'property' },
  { label: 'order', value: 'order: 0;', type: 'property' },
  { label: 'outline', value: 'outline: none;', type: 'property' },
  { label: 'outline-color', value: 'outline-color: invert;', type: 'property' },
  { label: 'outline-offset', value: 'outline-offset: 0;', type: 'property' },
  { label: 'outline-style', value: 'outline-style: none;', type: 'property' },
  { label: 'outline-width', value: 'outline-width: medium;', type: 'property' },
  { label: 'overflow', value: 'overflow: hidden;', type: 'property' },
  { label: 'overflow-wrap', value: 'overflow-wrap: normal;', type: 'property' },
  { label: 'overflow-x', value: 'overflow-x: hidden;', type: 'property' },
  { label: 'overflow-y', value: 'overflow-y: auto;', type: 'property' },
  { label: 'overscroll-behavior', value: 'overscroll-behavior: auto;', type: 'property' },

  // P
  { label: 'padding', value: 'padding: 0;', type: 'property' },
  { label: 'padding-bottom', value: 'padding-bottom: 0;', type: 'property' },
  { label: 'padding-left', value: 'padding-left: 0;', type: 'property' },
  { label: 'padding-right', value: 'padding-right: 0;', type: 'property' },
  { label: 'padding-top', value: 'padding-top: 0;', type: 'property' },
  { label: 'page-break-after', value: 'page-break-after: auto;', type: 'property' },
  { label: 'page-break-before', value: 'page-break-before: auto;', type: 'property' },
  { label: 'page-break-inside', value: 'page-break-inside: auto;', type: 'property' },
  { label: 'perspective', value: 'perspective: none;', type: 'property' },
  { label: 'perspective-origin', value: 'perspective-origin: 50% 50%;', type: 'property' },
  { label: 'place-content', value: 'place-content: center;', type: 'property' },
  { label: 'place-items', value: 'place-items: center;', type: 'property' },
  { label: 'place-self', value: 'place-self: center;', type: 'property' },
  { label: 'pointer-events', value: 'pointer-events: auto;', type: 'property' },
  { label: 'position', value: 'position: relative;', type: 'property' },

  // Q
  { label: 'quotes', value: 'quotes: none;', type: 'property' },

  // R
  { label: 'resize', value: 'resize: none;', type: 'property' },
  { label: 'right', value: 'right: 0;', type: 'property' },
  { label: 'rotate', value: 'rotate: 0deg;', type: 'property' },
  { label: 'row-gap', value: 'row-gap: normal;', type: 'property' },

  // S
  { label: 'scale', value: 'scale: 1;', type: 'property' },
  { label: 'scroll-behavior', value: 'scroll-behavior: smooth;', type: 'property' },
  { label: 'scroll-margin', value: 'scroll-margin: 0;', type: 'property' },
  { label: 'scroll-padding', value: 'scroll-padding: 0;', type: 'property' },
  { label: 'scroll-snap-align', value: 'scroll-snap-align: none;', type: 'property' },
  { label: 'scroll-snap-stop', value: 'scroll-snap-stop: normal;', type: 'property' },
  { label: 'scroll-snap-type', value: 'scroll-snap-type: none;', type: 'property' },
  { label: 'shape-image-threshold', value: 'shape-image-threshold: 0.0;', type: 'property' },
  { label: 'shape-margin', value: 'shape-margin: 0;', type: 'property' },
  { label: 'shape-outside', value: 'shape-outside: none;', type: 'property' },
  { label: 'shape-rendering', value: 'shape-rendering: auto;', type: 'property' },
  { label: 'stop-color', value: 'stop-color: black;', type: 'property' },
  { label: 'stop-opacity', value: 'stop-opacity: 1;', type: 'property' },
  { label: 'stroke', value: 'stroke: $0;', type: 'property' },
  { label: 'stroke-dasharray', value: 'stroke-dasharray: none;', type: 'property' },
  { label: 'stroke-dashoffset', value: 'stroke-dashoffset: 0;', type: 'property' },
  { label: 'stroke-linecap', value: 'stroke-linecap: butt;', type: 'property' },
  { label: 'stroke-linejoin', value: 'stroke-linejoin: miter;', type: 'property' },
  { label: 'stroke-miterlimit', value: 'stroke-miterlimit: 4;', type: 'property' },
  { label: 'stroke-opacity', value: 'stroke-opacity: 1;', type: 'property' },
  { label: 'stroke-width', value: 'stroke-width: 1;', type: 'property' },

  // T
  { label: 'tab-size', value: 'tab-size: 8;', type: 'property' },
  { label: 'table-layout', value: 'table-layout: auto;', type: 'property' },
  { label: 'text-align', value: 'text-align: center;', type: 'property' },
  { label: 'text-align-last', value: 'text-align-last: auto;', type: 'property' },
  { label: 'text-anchor', value: 'text-anchor: start;', type: 'property' },
  { label: 'text-decoration', value: 'text-decoration: none;', type: 'property' },
  { label: 'text-decoration-color', value: 'text-decoration-color: currentColor;', type: 'property' },
  { label: 'text-decoration-line', value: 'text-decoration-line: none;', type: 'property' },
  { label: 'text-decoration-style', value: 'text-decoration-style: solid;', type: 'property' },
  { label: 'text-decoration-thickness', value: 'text-decoration-thickness: auto;', type: 'property' },
  { label: 'text-indent', value: 'text-indent: 0;', type: 'property' },
  { label: 'text-justify', value: 'text-justify: auto;', type: 'property' },
  { label: 'text-orientation', value: 'text-orientation: mixed;', type: 'property' },
  { label: 'text-overflow', value: 'text-overflow: ellipsis;', type: 'property' },
  { label: 'text-rendering', value: 'text-rendering: auto;', type: 'property' },
  { label: 'text-shadow', value: 'text-shadow: none;', type: 'property' },
  { label: 'text-transform', value: 'text-transform: uppercase;', type: 'property' },
  { label: 'text-underline-offset', value: 'text-underline-offset: auto;', type: 'property' },
  { label: 'top', value: 'top: 0;', type: 'property' },
  { label: 'touch-action', value: 'touch-action: auto;', type: 'property' },
  { label: 'transform', value: 'transform: none;', type: 'property' },
  { label: 'transform-box', value: 'transform-box: view-box;', type: 'property' },
  { label: 'transform-origin', value: 'transform-origin: 50% 50%;', type: 'property' },
  { label: 'transform-style', value: 'transform-style: flat;', type: 'property' },
  { label: 'transition', value: 'transition: all 0.3s ease;', type: 'property' },
  { label: 'transition-delay', value: 'transition-delay: 0s;', type: 'property' },
  { label: 'transition-duration', value: 'transition-duration: 0s;', type: 'property' },
  { label: 'transition-property', value: 'transition-property: all;', type: 'property' },
  { label: 'transition-timing-function', value: 'transition-timing-function: ease;', type: 'property' },
  { label: 'translate', value: 'translate: none;', type: 'property' },

  // U
  { label: 'unicode-bidi', value: 'unicode-bidi: normal;', type: 'property' },
  { label: 'user-select', value: 'user-select: none;', type: 'property' },

  // V
  { label: 'vertical-align', value: 'vertical-align: middle;', type: 'property' },
  { label: 'visibility', value: 'visibility: visible;', type: 'property' },
  { label: 'vector-effect', value: 'vector-effect: none;', type: 'property' },

  // W
  { label: 'white-space', value: 'white-space: nowrap;', type: 'property' },
  { label: 'width', value: 'width: $0;', type: 'property' },
  { label: 'will-change', value: 'will-change: auto;', type: 'property' },
  { label: 'word-break', value: 'word-break: normal;', type: 'property' },
  { label: 'word-spacing', value: 'word-spacing: normal;', type: 'property' },
  { label: 'word-wrap', value: 'word-wrap: break-word;', type: 'property' },
  { label: 'writing-mode', value: 'writing-mode: horizontal-tb;', type: 'property' },

  // Z
  { label: 'z-index', value: 'z-index: 10;', type: 'property' },
];

export const JS_KEYWORDS: Suggestion[] = [
  { label: 'const', value: 'const $0', type: 'keyword' },
  { label: 'let', value: 'let $0', type: 'keyword' },
  { label: 'var', value: 'var $0', type: 'keyword' },
  { label: 'function', value: 'function name($0) {\n\t\n}', type: 'keyword' },
  { label: 'console.log', value: 'console.log($0);', type: 'snippet' },
  { label: 'console.error', value: 'console.error($0);', type: 'snippet' },
  { label: 'console.warn', value: 'console.warn($0);', type: 'snippet' },
  { label: 'if', value: 'if ($0) {\n\t\n}', type: 'keyword' },
  { label: 'else', value: 'else {\n\t$0\n}', type: 'keyword' },
  { label: 'else if', value: 'else if ($0) {\n\t\n}', type: 'keyword' },
  { label: 'for', value: 'for (let i = 0; i < n; i++) {\n\t$0\n}', type: 'keyword' },
  { label: 'while', value: 'while ($0) {\n\t\n}', type: 'keyword' },
  { label: 'do', value: 'do {\n\t$0\n} while ();', type: 'keyword' },
  { label: 'switch', value: 'switch ($0) {\n\tcase value:\n\t\tbreak;\n\tdefault:\n\t\tbreak;\n}', type: 'keyword' },
  { label: 'document.getElementById', value: "document.getElementById('$0')", type: 'snippet' },
  { label: 'document.querySelector', value: "document.querySelector('$0')", type: 'snippet' },
  { label: 'document.querySelectorAll', value: "document.querySelectorAll('$0')", type: 'snippet' },
  { label: 'document.createElement', value: "document.createElement('$0')", type: 'snippet' },
  { label: 'addEventListener', value: "addEventListener('click', () => {\n\t$0\n});", type: 'snippet' },
  { label: 'removeEventListener', value: "removeEventListener('click', handler);", type: 'snippet' },
  { label: 'return', value: 'return $0;', type: 'keyword' },
  { label: 'map', value: 'map((item) => $0)', type: 'snippet' },
  { label: 'filter', value: 'filter((item) => $0)', type: 'snippet' },
  { label: 'forEach', value: 'forEach((item) => {\n\t$0\n})', type: 'snippet' },
  { label: 'reduce', value: 'reduce((acc, curr) => $0, initial)', type: 'snippet' },
  { label: 'find', value: 'find((item) => $0)', type: 'snippet' },
  { label: 'includes', value: 'includes($0)', type: 'snippet' },
  { label: 'indexOf', value: 'indexOf($0)', type: 'snippet' },
  { label: 'push', value: 'push($0)', type: 'snippet' },
  { label: 'pop', value: 'pop()', type: 'snippet' },
  { label: 'shift', value: 'shift()', type: 'snippet' },
  { label: 'unshift', value: 'unshift($0)', type: 'snippet' },
  { label: 'splice', value: 'splice(start, deleteCount)', type: 'snippet' },
  { label: 'slice', value: 'slice(start, end)', type: 'snippet' },
  { label: 'split', value: "split('')", type: 'snippet' },
  { label: 'join', value: "join('')", type: 'snippet' },
  { label: 'JSON.stringify', value: 'JSON.stringify($0)', type: 'snippet' },
  { label: 'JSON.parse', value: 'JSON.parse($0)', type: 'snippet' },
  { label: 'Math.random', value: 'Math.random()', type: 'snippet' },
  { label: 'Math.floor', value: 'Math.floor($0)', type: 'snippet' },
  { label: 'Math.ceil', value: 'Math.ceil($0)', type: 'snippet' },
  { label: 'Math.round', value: 'Math.round($0)', type: 'snippet' },
  { label: 'setTimeout', value: 'setTimeout(() => {\n\t$0\n}, 1000);', type: 'snippet' },
  { label: 'setInterval', value: 'setInterval(() => {\n\t$0\n}, 1000);', type: 'snippet' },
  { label: 'fetch', value: "fetch('$0')\n\t.then(res => res.json())\n\t.then(data => console.log(data));", type: 'snippet' },
  { label: 'async', value: 'async function name() {\n\t$0\n}', type: 'keyword' },
  { label: 'await', value: 'await $0', type: 'keyword' },
  { label: 'try', value: 'try {\n\t$0\n} catch (error) {\n\tconsole.error(error);\n}', type: 'keyword' },
  { label: 'class', value: 'class Name {\n\tconstructor() {\n\t\t$0\n\t}\n}', type: 'keyword' },
  { label: 'import', value: "import { $0 } from '';", type: 'keyword' },
  { label: 'export', value: 'export default $0;', type: 'keyword' },
];