import { Suggestion } from './types';

// $0 represents where the cursor will be placed after insertion

export const HTML_TAGS: Suggestion[] = [
  // --- Snippets & Boilerplate ---
  { label: '!', value: '<!DOCTYPE html>\n<html lang="en">\n<head>\n\t<meta charset="UTF-8" />\n\t<meta name="viewport" content="width=device-width, initial-scale=1.0" />\n\t<title>Document</title>\n</head>\n<body>\n\t$0\n</body>\n</html>', type: 'snippet', detail: 'HTML5 Boilerplate' },
  { label: 'html:5', value: '<!DOCTYPE html>\n<html lang="en">\n<head>\n\t<meta charset="UTF-8" />\n\t<meta name="viewport" content="width=device-width, initial-scale=1.0" />\n\t<title>Document</title>\n</head>\n<body>\n\t$0\n</body>\n</html>', type: 'snippet', detail: 'HTML5 Boilerplate' },
  { label: 'meta:utf', value: '<meta charset="UTF-8" />', type: 'tag', detail: 'UTF-8 Charset' },
  { label: 'meta:vp', value: '<meta name="viewport" content="width=device-width, initial-scale=1.0" />', type: 'tag', detail: 'Viewport Settings' },
  { label: 'link:css', value: '<link rel="stylesheet" href="style.css" />', type: 'tag', detail: 'Link CSS' },
  { label: 'script:src', value: '<script src="$0"></script>', type: 'tag', detail: 'External Script' },

  // --- A to Z Tags ---
  { label: 'a', value: '<a href="$0"></a>', type: 'tag', detail: 'Anchor' },
  { label: 'abbr', value: '<abbr title="$0"></abbr>', type: 'tag', detail: 'Abbreviation' },
  { label: 'address', value: '<address>$0</address>', type: 'tag', detail: 'Contact Info' },
  { label: 'area', value: '<area shape="" coords="" href="" alt="" />', type: 'tag', detail: 'Image Map Area' },
  { label: 'article', value: '<article>$0</article>', type: 'tag', detail: 'Article' },
  { label: 'aside', value: '<aside>$0</aside>', type: 'tag', detail: 'Sidebar' },
  { label: 'audio', value: '<audio src="$0" controls></audio>', type: 'tag', detail: 'Audio Player' },
  { label: 'b', value: '<b>$0</b>', type: 'tag', detail: 'Bold' },
  { label: 'base', value: '<base href="$0" />', type: 'tag', detail: 'Base URL' },
  { label: 'bdi', value: '<bdi>$0</bdi>', type: 'tag', detail: 'Bi-directional Isolation' },
  { label: 'bdo', value: '<bdo dir="">$0</bdo>', type: 'tag', detail: 'Bi-directional Override' },
  { label: 'blockquote', value: '<blockquote>$0</blockquote>', type: 'tag', detail: 'Block Quote' },
  { label: 'body', value: '<body>\n\t$0\n</body>', type: 'tag', detail: 'Document Body' },
  { label: 'br', value: '<br />', type: 'tag', detail: 'Line Break' },
  { label: 'button', value: '<button type="button">$0</button>', type: 'tag', detail: 'Button' },
  { label: 'canvas', value: '<canvas id="$0" width="300" height="150"></canvas>', type: 'tag', detail: 'Graphics Canvas' },
  { label: 'caption', value: '<caption>$0</caption>', type: 'tag', detail: 'Table Caption' },
  { label: 'cite', value: '<cite>$0</cite>', type: 'tag', detail: 'Citation' },
  { label: 'code', value: '<code>$0</code>', type: 'tag', detail: 'Inline Code' },
  { label: 'col', value: '<col span="" class="" />', type: 'tag', detail: 'Table Column' },
  { label: 'colgroup', value: '<colgroup>\n\t<col />\n</colgroup>', type: 'tag', detail: 'Column Group' },
  { label: 'data', value: '<data value="">$0</data>', type: 'tag', detail: 'Machine Readable Data' },
  { label: 'datalist', value: '<datalist id="">\n\t<option value="">\n</datalist>', type: 'tag', detail: 'Input Suggestions' },
  { label: 'dd', value: '<dd>$0</dd>', type: 'tag', detail: 'Description Details' },
  { label: 'del', value: '<del>$0</del>', type: 'tag', detail: 'Deleted Text' },
  { label: 'details', value: '<details>\n\t<summary>Title</summary>\n\t$0\n</details>', type: 'tag', detail: 'Disclosure Widget' },
  { label: 'dfn', value: '<dfn>$0</dfn>', type: 'tag', detail: 'Definition' },
  { label: 'dialog', value: '<dialog open>$0</dialog>', type: 'tag', detail: 'Dialog Box' },
  { label: 'div', value: '<div>$0</div>', type: 'tag', detail: 'Division' },
  { label: 'dl', value: '<dl>\n\t<dt></dt>\n\t<dd></dd>\n</dl>', type: 'tag', detail: 'Description List' },
  { label: 'dt', value: '<dt>$0</dt>', type: 'tag', detail: 'Description Term' },
  { label: 'em', value: '<em>$0</em>', type: 'tag', detail: 'Emphasis' },
  { label: 'embed', value: '<embed src="$0" type="" />', type: 'tag', detail: 'External Content' },
  { label: 'fieldset', value: '<fieldset>\n\t<legend>$0</legend>\n</fieldset>', type: 'tag', detail: 'Form Group' },
  { label: 'figcaption', value: '<figcaption>$0</figcaption>', type: 'tag', detail: 'Figure Caption' },
  { label: 'figure', value: '<figure>\n\t<img src="" alt="" />\n\t<figcaption>$0</figcaption>\n</figure>', type: 'tag', detail: 'Figure' },
  { label: 'footer', value: '<footer>$0</footer>', type: 'tag', detail: 'Footer' },
  { label: 'form', value: '<form action="$0" method="POST"></form>', type: 'tag', detail: 'Form' },
  { label: 'h1', value: '<h1>$0</h1>', type: 'tag', detail: 'Heading 1' },
  { label: 'h2', value: '<h2>$0</h2>', type: 'tag', detail: 'Heading 2' },
  { label: 'h3', value: '<h3>$0</h3>', type: 'tag', detail: 'Heading 3' },
  { label: 'h4', value: '<h4>$0</h4>', type: 'tag', detail: 'Heading 4' },
  { label: 'h5', value: '<h5>$0</h5>', type: 'tag', detail: 'Heading 5' },
  { label: 'h6', value: '<h6>$0</h6>', type: 'tag', detail: 'Heading 6' },
  { label: 'head', value: '<head>\n\t$0\n</head>', type: 'tag', detail: 'Document Head' },
  { label: 'header', value: '<header>$0</header>', type: 'tag', detail: 'Header' },
  { label: 'hgroup', value: '<hgroup>\n\t<h1></h1>\n\t<h2></h2>\n</hgroup>', type: 'tag', detail: 'Heading Group' },
  { label: 'hr', value: '<hr />', type: 'tag', detail: 'Horizontal Rule' },
  { label: 'html', value: '<html lang="en">\n$0\n</html>', type: 'tag', detail: 'Root Element' },
  { label: 'i', value: '<i>$0</i>', type: 'tag', detail: 'Italic' },
  { label: 'iframe', value: '<iframe src="$0" frameborder="0"></iframe>', type: 'tag', detail: 'Inline Frame' },
  { label: 'img', value: '<img src="$0" alt="" />', type: 'tag', detail: 'Image' },
  { label: 'input', value: '<input type="text" placeholder="$0" />', type: 'tag', detail: 'Input Field' },
  { label: 'input:checkbox', value: '<input type="checkbox" id="" />', type: 'tag', detail: 'Checkbox' },
  { label: 'input:email', value: '<input type="email" placeholder="" />', type: 'tag', detail: 'Email Input' },
  { label: 'input:file', value: '<input type="file" />', type: 'tag', detail: 'File Upload' },
  { label: 'input:hidden', value: '<input type="hidden" value="" />', type: 'tag', detail: 'Hidden Input' },
  { label: 'input:password', value: '<input type="password" placeholder="" />', type: 'tag', detail: 'Password Input' },
  { label: 'input:radio', value: '<input type="radio" name="" id="" />', type: 'tag', detail: 'Radio Button' },
  { label: 'input:submit', value: '<input type="submit" value="Submit" />', type: 'tag', detail: 'Submit Button' },
  { label: 'ins', value: '<ins>$0</ins>', type: 'tag', detail: 'Inserted Text' },
  { label: 'kbd', value: '<kbd>$0</kbd>', type: 'tag', detail: 'Keyboard Input' },
  { label: 'label', value: '<label for="$0"></label>', type: 'tag', detail: 'Input Label' },
  { label: 'legend', value: '<legend>$0</legend>', type: 'tag', detail: 'Fieldset Legend' },
  { label: 'li', value: '<li>$0</li>', type: 'tag', detail: 'List Item' },
  { label: 'link', value: '<link rel="stylesheet" href="$0" />', type: 'tag', detail: 'Resource Link' },
  { label: 'main', value: '<main>$0</main>', type: 'tag', detail: 'Main Content' },
  { label: 'map', value: '<map name="">$0</map>', type: 'tag', detail: 'Image Map' },
  { label: 'mark', value: '<mark>$0</mark>', type: 'tag', detail: 'Marked Text' },
  { label: 'meta', value: '<meta name="viewport" content="width=device-width, initial-scale=1.0" />', type: 'tag', detail: 'Metadata' },
  { label: 'meter', value: '<meter value="" min="" max="">$0</meter>', type: 'tag', detail: 'Scalar Measurement' },
  { label: 'nav', value: '<nav>$0</nav>', type: 'tag', detail: 'Navigation' },
  { label: 'noscript', value: '<noscript>$0</noscript>', type: 'tag', detail: 'No Script Fallback' },
  { label: 'object', value: '<object data="" type="">$0</object>', type: 'tag', detail: 'External Object' },
  { label: 'ol', value: '<ol>\n\t<li>$0</li>\n</ol>', type: 'tag', detail: 'Ordered List' },
  { label: 'optgroup', value: '<optgroup label="">$0</optgroup>', type: 'tag', detail: 'Option Group' },
  { label: 'option', value: '<option value="$0"></option>', type: 'tag', detail: 'Select Option' },
  { label: 'output', value: '<output name="">$0</output>', type: 'tag', detail: 'Calculation Output' },
  { label: 'p', value: '<p>$0</p>', type: 'tag', detail: 'Paragraph' },
  { label: 'param', value: '<param name="" value="" />', type: 'tag', detail: 'Object Parameter' },
  { label: 'picture', value: '<picture>\n\t<source srcset="" type="" />\n\t<img src="" alt="" />\n</picture>', type: 'tag', detail: 'Picture' },
  { label: 'pre', value: '<pre>$0</pre>', type: 'tag', detail: 'Preformatted Text' },
  { label: 'progress', value: '<progress value="" max="">$0</progress>', type: 'tag', detail: 'Progress Bar' },
  { label: 'q', value: '<q>$0</q>', type: 'tag', detail: 'Inline Quote' },
  { label: 'rp', value: '<rp>$0</rp>', type: 'tag', detail: 'Ruby Parenthesis' },
  { label: 'rt', value: '<rt>$0</rt>', type: 'tag', detail: 'Ruby Text' },
  { label: 'ruby', value: '<ruby>$0</ruby>', type: 'tag', detail: 'Ruby Annotation' },
  { label: 's', value: '<s>$0</s>', type: 'tag', detail: 'Strikethrough' },
  { label: 'samp', value: '<samp>$0</samp>', type: 'tag', detail: 'Sample Output' },
  { label: 'script', value: '<script src="$0"></script>', type: 'tag', detail: 'Script' },
  { label: 'section', value: '<section>$0</section>', type: 'tag', detail: 'Section' },
  { label: 'select', value: '<select name="$0" id=""></select>', type: 'tag', detail: 'Select Menu' },
  { label: 'small', value: '<small>$0</small>', type: 'tag', detail: 'Small Text' },
  { label: 'source', value: '<source src="$0" type="video/mp4" />', type: 'tag', detail: 'Media Source' },
  { label: 'span', value: '<span>$0</span>', type: 'tag', detail: 'Generic Inline' },
  { label: 'strong', value: '<strong>$0</strong>', type: 'tag', detail: 'Strong Importance' },
  { label: 'style', value: '<style>\n\t$0\n</style>', type: 'tag', detail: 'Internal CSS' },
  { label: 'sub', value: '<sub>$0</sub>', type: 'tag', detail: 'Subscript' },
  { label: 'summary', value: '<summary>$0</summary>', type: 'tag', detail: 'Details Summary' },
  { label: 'sup', value: '<sup>$0</sup>', type: 'tag', detail: 'Superscript' },
  { label: 'svg', value: '<svg width="100" height="100" viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">\n\t$0\n</svg>', type: 'tag', detail: 'SVG Graphics' },
  { label: 'table', value: '<table>\n\t<thead>\n\t\t<tr>\n\t\t\t<th>$0</th>\n\t\t</tr>\n\t</thead>\n\t<tbody>\n\t\t<tr>\n\t\t\t<td></td>\n\t\t</tr>\n\t</tbody>\n</table>', type: 'tag', detail: 'Table' },
  { label: 'tbody', value: '<tbody>$0</tbody>', type: 'tag', detail: 'Table Body' },
  { label: 'td', value: '<td>$0</td>', type: 'tag', detail: 'Table Data' },
  { label: 'template', value: '<template>\n\t$0\n</template>', type: 'tag', detail: 'Content Template' },
  { label: 'textarea', value: '<textarea name="$0" id="" cols="30" rows="10"></textarea>', type: 'tag', detail: 'Text Input Area' },
  { label: 'tfoot', value: '<tfoot>$0</tfoot>', type: 'tag', detail: 'Table Footer' },
  { label: 'th', value: '<th>$0</th>', type: 'tag', detail: 'Table Header' },
  { label: 'thead', value: '<thead>$0</thead>', type: 'tag', detail: 'Table Head' },
  { label: 'time', value: '<time datetime="">$0</time>', type: 'tag', detail: 'Date/Time' },
  { label: 'title', value: '<title>$0</title>', type: 'tag', detail: 'Document Title' },
  { label: 'tr', value: '<tr>$0</tr>', type: 'tag', detail: 'Table Row' },
  { label: 'track', value: '<track src="" kind="" srclang="" label="" />', type: 'tag', detail: 'Media Track' },
  { label: 'u', value: '<u>$0</u>', type: 'tag', detail: 'Underline' },
  { label: 'ul', value: '<ul>\n\t<li>$0</li>\n</ul>', type: 'tag', detail: 'Unordered List' },
  { label: 'var', value: '<var>$0</var>', type: 'tag', detail: 'Variable' },
  { label: 'video', value: '<video src="$0" controls></video>', type: 'tag', detail: 'Video Player' },
  { label: 'wbr', value: '<wbr />', type: 'tag', detail: 'Word Break' },

  // --- SVG Tags ---
  { label: 'path', value: '<path d="$0" fill="none" stroke="black" />', type: 'tag', detail: 'SVG Path' },
  { label: 'rect', value: '<rect x="0" y="0" width="100" height="100" fill="black" />', type: 'tag', detail: 'SVG Rect' },
  { label: 'circle', value: '<circle cx="50" cy="50" r="40" fill="black" />', type: 'tag', detail: 'SVG Circle' },
  { label: 'g', value: '<g>\n\t$0\n</g>', type: 'tag', detail: 'SVG Group' },
  { label: 'defs', value: '<defs>\n\t$0\n</defs>', type: 'tag', detail: 'SVG Definitions' },
  
  // --- Attributes ---
  { label: 'class', value: 'class="$0"', type: 'property', detail: 'Class Name' },
  { label: 'id', value: 'id="$0"', type: 'property', detail: 'Unique ID' },
  { label: 'style', value: 'style="$0"', type: 'property', detail: 'Inline Style' },
  { label: 'src', value: 'src="$0"', type: 'property', detail: 'Source URL' },
  { label: 'href', value: 'href="$0"', type: 'property', detail: 'Hyperlink Ref' },
  { label: 'alt', value: 'alt="$0"', type: 'property', detail: 'Alt Text' },
  { label: 'type', value: 'type="$0"', type: 'property', detail: 'Input Type' },
  { label: 'width', value: 'width="$0"', type: 'property', detail: 'Width' },
  { label: 'height', value: 'height="$0"', type: 'property', detail: 'Height' },
  { label: 'placeholder', value: 'placeholder="$0"', type: 'property', detail: 'Input Hint' },
  { label: 'required', value: 'required', type: 'property', detail: 'Required Flag' },
  { label: 'disabled', value: 'disabled', type: 'property', detail: 'Disabled Flag' },
  { label: 'checked', value: 'checked', type: 'property', detail: 'Checked Flag' },
  { label: 'selected', value: 'selected', type: 'property', detail: 'Selected Flag' },
];

export const CSS_PROPS: Suggestion[] = [
  // Common
  { label: 'display', value: 'display: flex;', type: 'property', detail: 'Layout Mode' },
  { label: 'flex', value: 'flex: 1;', type: 'property', detail: 'Flex Grow/Shrink' },
  { label: 'color', value: 'color: $0;', type: 'property', detail: 'Text Color' },
  { label: 'background', value: 'background: $0;', type: 'property', detail: 'Background' },
  { label: 'background-color', value: 'background-color: $0;', type: 'property', detail: 'BG Color' },
  { label: 'margin', value: 'margin: 0;', type: 'property', detail: 'Outer Spacing' },
  { label: 'padding', value: 'padding: 0;', type: 'property', detail: 'Inner Spacing' },
  { label: 'border', value: 'border: 1px solid $0;', type: 'property', detail: 'Border' },
  { label: 'font-size', value: 'font-size: 16px;', type: 'property', detail: 'Font Size' },
  { label: 'font-family', value: 'font-family: sans-serif;', type: 'property', detail: 'Font Family' },
  { label: 'width', value: 'width: 100%;', type: 'property', detail: 'Width' },
  { label: 'height', value: 'height: 100vh;', type: 'property', detail: 'Height' },
  { label: 'position', value: 'position: absolute;', type: 'property', detail: 'Positioning' },
  { label: 'top', value: 'top: 0;', type: 'property', detail: 'Top Offset' },
  { label: 'left', value: 'left: 0;', type: 'property', detail: 'Left Offset' },
  { label: 'right', value: 'right: 0;', type: 'property', detail: 'Right Offset' },
  { label: 'bottom', value: 'bottom: 0;', type: 'property', detail: 'Bottom Offset' },
  { label: 'z-index', value: 'z-index: 10;', type: 'property', detail: 'Stack Order' },
  { label: 'text-align', value: 'text-align: center;', type: 'property', detail: 'Text Align' },
  { label: 'justify-content', value: 'justify-content: center;', type: 'property', detail: 'Flex Justify' },
  { label: 'align-items', value: 'align-items: center;', type: 'property', detail: 'Flex Align' },
  { label: 'cursor', value: 'cursor: pointer;', type: 'property', detail: 'Mouse Cursor' },
  { label: 'overflow', value: 'overflow: hidden;', type: 'property', detail: 'Overflow Handling' },
  { label: 'box-shadow', value: 'box-shadow: 0 4px 6px rgba(0,0,0,0.1);', type: 'property', detail: 'Shadow' },
  { label: 'border-radius', value: 'border-radius: 4px;', type: 'property', detail: 'Corner Radius' },
  { label: 'transition', value: 'transition: all 0.3s ease;', type: 'property', detail: 'Animation' },
  { label: 'transform', value: 'transform: translate(-50%, -50%);', type: 'property', detail: 'Transformation' },
  { label: 'opacity', value: 'opacity: 0.5;', type: 'property', detail: 'Transparency' },
  // ... Add more as needed, this covers standard usage
];

export const JS_KEYWORDS: Suggestion[] = [
  { label: 'const', value: 'const $0', type: 'keyword', detail: 'Constant' },
  { label: 'let', value: 'let $0', type: 'keyword', detail: 'Variable' },
  { label: 'var', value: 'var $0', type: 'keyword', detail: 'Variable (Legacy)' },
  { label: 'function', value: 'function name($0) {\n\t\n}', type: 'keyword', detail: 'Function Decl' },
  { label: 'console.log', value: 'console.log($0);', type: 'snippet', detail: 'Log Output' },
  { label: 'if', value: 'if ($0) {\n\t\n}', type: 'keyword', detail: 'Condition' },
  { label: 'else', value: 'else {\n\t$0\n}', type: 'keyword', detail: 'Else' },
  { label: 'for', value: 'for (let i = 0; i < n; i++) {\n\t$0\n}', type: 'keyword', detail: 'For Loop' },
  { label: 'while', value: 'while ($0) {\n\t\n}', type: 'keyword', detail: 'While Loop' },
  { label: 'document.getElementById', value: "document.getElementById('$0')", type: 'snippet', detail: 'Get Element by ID' },
  { label: 'document.querySelector', value: "document.querySelector('$0')", type: 'snippet', detail: 'Query Selector' },
  { label: 'addEventListener', value: "addEventListener('click', () => {\n\t$0\n});", type: 'snippet', detail: 'Event Listener' },
  { label: 'return', value: 'return $0;', type: 'keyword', detail: 'Return' },
  { label: 'map', value: 'map((item) => $0)', type: 'snippet', detail: 'Array Map' },
  { label: 'filter', value: 'filter((item) => $0)', type: 'snippet', detail: 'Array Filter' },
  { label: 'forEach', value: 'forEach((item) => {\n\t$0\n})', type: 'snippet', detail: 'Array ForEach' },
  { label: 'fetch', value: "fetch('$0')\n\t.then(res => res.json())\n\t.then(data => console.log(data));", type: 'snippet', detail: 'Fetch API' },
  { label: 'async', value: 'async function name() {\n\t$0\n}', type: 'keyword', detail: 'Async Function' },
  { label: 'await', value: 'await $0', type: 'keyword', detail: 'Await' },
  { label: 'import', value: "import { $0 } from '';", type: 'keyword', detail: 'Import Module' },
  { label: 'export', value: 'export default $0;', type: 'keyword', detail: 'Export Module' },
  { label: 'class', value: 'class Name {\n\tconstructor() {\n\t\t$0\n\t}\n}', type: 'keyword', detail: 'Class' },
];